Repository openshift-kni/performance-addon-operators, pull requests merged in 2020-02, with the labels that each got.

#70 functests: fix CI tests to pass on the latest OpenShift
  functests/utils/nodes/nodes.go
Labels: approved, lgtm, size/XS

#69 functests: use controller-runtime client
  functests/performance/performance.go
  functests/performance/rt-kernel.go
  functests/performance/topology_manager.go
  functests/test_suite_test.go
  functests/utils/client/clients.go
  functests/utils/machineconfigpool/machineconfigpool.go
  functests/utils/namespaces/namespaces.go
  functests/utils/nodes/nodes.go
  functests/utils/pods/pods.go
Labels: approved, lgtm, size/L

#67 Improved cleanup script
  hack/clean-deploy.sh
Labels: approved, lgtm, size/M

#74 csvgen: extend to accomodate OCP needs
  hack/csv-generate.sh
  tools/csv-generator/csv-generator.go
Labels: approved, lgtm, size/M

#66 Fix the number of reserved CPUs
  cluster-setup/base/performance/performance_profile.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#77 Fix pre-boot tuning to check latest boot entry
  build/assets/scripts/pre-boot-tuning.sh
Labels: approved, lgtm, size/S

#60 Add possibility to specify NUMA node for hugepages allocation
  build/assets/scripts/hugepages-allocation.sh
  cluster-setup/base/performance/performance_profile.yaml
  deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml
  functests/performance/hugepages.go
  functests/utils/profiles/profiles.go
  pkg/apis/performance/v1alpha1/performanceprofile_types.go
  pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/controller/performanceprofile/components/profile/profile.go
  pkg/controller/performanceprofile/components/profile/profile_test.go
  pkg/controller/performanceprofile/components/utils.go
  pkg/controller/performanceprofile/performanceprofile_controller.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
Labels: approved, lgtm, size/L

#78 let taskset use the reserved CPUs list instead of a mask
  build/assets/scripts/pre-boot-tuning.sh
Labels: approved, lgtm, size/XS

#68 Added test verifying basic hugepages usage by pods
  functests/performance/hugepages.go
  functests/utils/pods/pods.go
Labels: approved, lgtm, ok-to-test, size/L

#81 Move environment specific parameters from the base yaml
  cluster-setup/base/performance/performance_profile.yaml
  cluster-setup/ci-cluster/performance/performance_profile.patch.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance-addon-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#71 Added test verifying CPU affinity and reservation
  functests/performance/cpu_management.go
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_suite_test.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_test.go
Labels: approved, lgtm, ok-to-test, size/L

#73 API Isolated and NonIsolated CPU changes
  build/assets/scripts/pre-boot-tuning.sh
  build/assets/tuned/openshift-node-real-time-kernel
  cluster-setup/base/performance/performance_profile.yaml
  deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/crds/performance.openshift.io_v1alpha1_performanceprofile_cr.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance-addon-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml
  pkg/apis/performance/v1alpha1/performanceprofile_types.go
  pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/controller/performanceprofile/components/profile/profile.go
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
  pkg/utils/testing/testing.go
Labels: approved, lgtm, size/L

#85 Explicitly set HOME env variable
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#80 Adjust pre boot tunings
  build/assets/scripts/pre-boot-tuning.sh
  build/assets/tuned/openshift-node-real-time-kernel
  cluster-setup/ci-cluster/performance/performance_profile.patch.yaml
  functests/performance/cpu_management.go
  functests/performance/performance.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/utils.go
  pkg/controller/performanceprofile/components/utils_suite_test.go
  pkg/controller/performanceprofile/components/utils_test.go
Labels: approved, lgtm, size/L

#88 Fix for CPU management test
  cluster-setup/ci-cluster/performance/performance_profile.patch.yaml
  functests/performance/cpu_management.go
Labels: approved, lgtm, ok-to-test, size/S

#89 Fix Cpumask for workqueues
  functests/performance/performance.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/utils.go
  pkg/controller/performanceprofile/components/utils_test.go
Labels: approved, lgtm, size/M

#83 csv: add more metadata
  Makefile
  hack/csv-generate.sh
  tools/csv-generator/csv-generator.go
Labels: approved, lgtm, size/M

#91 [release-4.4] Use correct operator tag in upstream registry image
  openshift-ci/Dockerfile.registry.upstream.dev
Labels: approved, lgtm, size/XS

#93 Add nil check before creating preboot ignition
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
Labels: approved, lgtm, size/M

#95 Improve mask util function to remove trailing zeros
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/utils.go
  pkg/controller/performanceprofile/components/utils_test.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
Labels: approved, lgtm, size/M

#94 Fix events permissions
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance-addon-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#100 Added slintes to approvers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#99 Fixed CR example
  deploy/crds/performance.openshift.io_v1alpha1_performanceprofile_cr.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance-addon-operator.v0.0.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#105 fix lingering mod vendor issues in master via deps-update
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_suite_test.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_test.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/M
