Repository openshift-kni/performance-addon-operators, pull requests merged in 2020-05, with the labels that each got.

#203 Fix CI by using shorter names...
  cluster-setup/base/performance/operator_catalogsource.yaml
  cluster-setup/base/performance/operator_operatorgroup.yaml
  cluster-setup/base/performance/operator_subscription.yaml
Labels: approved, lgtm

#201 Don't wait for mcp to be updating if the performance profile was created previously
  functests/0_config/config.go
Labels: approved, lgtm

#202 Smaller build image
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#205 Fix CI build image, don't use root
  openshift-ci/Dockerfile.tools
Labels: approved

#206 Fix CI, don't use root
  openshift-ci/Dockerfile.tools
Labels: approved

#209 Set permission on $HOME at the end
  openshift-ci/Dockerfile.tools
Labels: approved

#210 Fix build image
  openshift-ci/Dockerfile.tools
Labels: approved

#197 Add test case to test performance profile message
  functests/3_performance_status/status.go
  functests/3_performance_status/test_suite_performance_status_test.go
  functests/utils/mcps/mcps.go
  functests/utils/profiles/profiles.go
  go.sum
Labels: approved, lgtm, ok-to-test

#213 Added coverage to contributing guide, and badges to README
  CONTRIBUTING.md
  README.md
Labels: approved, lgtm

#214 cleanup: streamline and use csv-generator options
  hack/csv-generate.sh
  tools/csv-generator/csv-generator.go
Labels: approved, lgtm

#204 Added CSV and subscription channels
  cluster-setup/base/performance/operator_subscription.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.0/performance-addon-operator.v4.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.0/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.0/performance-addon-operator.v4.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.0/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  hack/csv-generate.sh
Labels: approved, lgtm

#220 [release-4.4] align the csv processing tools with the improvements in the 4.5 branch
  .gitignore
  Makefile
  hack/csv-generate.sh
  pkg/utils/csvtools/csvtools.go
  tools/csv-generator/csv-generator.go
  tools/csv-replace-imageref/csv-replace-imageref.go
Labels: approved, lgtm

#212 Improved release doc.
  docs/releasing.md
Labels: approved, lgtm

#223 [release-4.5] Update default tag
  Makefile
Labels: approved, lgtm

#222 [release-4.4] Updated default tag
  Makefile
Labels: approved, lgtm

#224 Updated default tag
  Makefile
Labels: approved, lgtm

#229 [release-4.4] Fixed registry image
  openshift-ci/Dockerfile.registry.upstream.dev
Labels: approved, lgtm

#228 [release-4.5] Fixed registry image
  openshift-ci/Dockerfile.registry.upstream.dev
Labels: approved, lgtm

#227 Fixed registry image
  functests/utils/mcps/mcps.go
  openshift-ci/Dockerfile.registry.upstream.dev
Labels: approved, lgtm

#225 Use the cnf tests image as container image for tests pod.
  functests/1_performance/cpu_management.go
  functests/1_performance/hugepages.go
  functests/utils/images/images.go
  functests/utils/pods/pods.go
Labels: approved, lgtm

#231 Update csv-generator.go
  tools/csv-generator/csv-generator.go
Labels: approved, lgtm, needs-ok-to-test

#221 Fix names in clean-deploy.sh script
  hack/clean-deploy.sh
Labels: approved, lgtm

#234 [release-4.4] Add test id's to tests in 4.4 release branch
  functests/performance/cpu_management.go
  functests/performance/performance.go
  functests/performance/rt-kernel.go
  functests/performance/topology_manager.go
Labels: approved, lgtm, ok-to-test

#238 [release-4.4] Divide updating profile tests
  functests/performance/updating_profile.go
  functests/utils/utils.go
Labels: approved, lgtm

#237 Increase the waiting timeout for the stress pod, now using the cnf tests image
  functests/1_performance/cpu_management.go
  functests/1_performance/hugepages.go
Labels: approved, lgtm

#190 Refactor functionallity to use NTO with machine config support
  build/assets/scripts/pre-boot-tuning.sh
  build/assets/scripts/reboot.sh
  build/assets/tuned/openshift-node-performance
  docs/troubleshooting.md
  functests/1_performance/performance.go
  functests/2_performance_update/updating_profile.go
  functests/utils/consts.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/controller/performanceprofile/components/profile/profile.go
  pkg/controller/performanceprofile/components/profile/profile_test.go
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
  pkg/utils/testing/testing.go
Labels: approved, lgtm

#242 kubelet.conf has some nicer formatting now on the nodes...
  functests/1_performance/cpu_management.go
  functests/2_performance_update/updating_profile.go
Labels: approved, lgtm

#226 Add performance operator upgrade test 4.4.0->4.5.0
  Makefile
  cluster-setup/upgrade-test-cluster/performance/kustomization.yaml
  cluster-setup/upgrade-test-cluster/performance/operator_subscription.patch.yaml
  cluster-setup/upgrade-test-cluster/performance/performance_profile.yaml
  functests-extended/1_performance_operator_upgrade/test_suite_performance_operator_upgrade_test.go
  functests-extended/1_performance_operator_upgrade/upgrade_operator.go
  functests/utils/client/clients.go
  go.mod
  hack/clean-deploy.sh
  hack/run-upgrade-tests.sh
  vendor/k8s.io/apiextensions-apiserver/LICENSE
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#241 Better retry for getting resources in tests
  functests/utils/client/clients.go
Labels: approved, lgtm

#243 [release-4.5] kubelet.conf has some nicer formatting now on the nodes...
  functests/1_performance/cpu_management.go
  functests/2_performance_update/updating_profile.go
Labels: approved, lgtm

#246 Added CI doc
  docs/ci.md
Labels: approved, lgtm

#240 Revert "Workaround oc behaviour change after rebase on k8s 1.18"
  hack/deploy.sh
Labels: approved, lgtm

#251 e2e: hugepages: add wait on calculation of allocated hugepages
  functests/1_performance/hugepages.go
Labels: approved, lgtm

#253 [release-4.4] Backport updating profile tests
  functests/performance/updating_profile.go
  functests/utils/mcps/mcps.go
Labels: approved, lgtm

#254 Make it possible to override the performance profile used in tests.
  functests/0_config/config.go
Labels: approved, lgtm

#255 [release-4.4] Backport setAffinity test
  functests/performance/performance.go
Labels: approved, lgtm

#257 Fix realtime kernel argument in base profile
  build/assets/tuned/openshift-node-performance
  functests/1_performance/performance.go
  functests/2_performance_update/updating_profile.go
  functests/3_performance_status/status.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
Labels: approved, lgtm

#249 Add tuned status field
  deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance.openshift.io_performanceprofiles_crd.yaml
  docs/performance_profile.md
  functests/3_performance_status/status.go
  pkg/apis/performance/v1alpha1/performanceprofile_types.go
  pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
  pkg/controller/performanceprofile/status.go
Labels: approved, lgtm

#260 fix for cleaning script
  hack/clean-deploy.sh
Labels: approved, lgtm

#259 Configuration hotfixes documentation
  docs/configuration_hotfixes.md
  docs/troubleshooting.md
Labels: approved, lgtm

#263 fix for operator upgrade test
  functests-extended/1_performance_operator_upgrade/upgrade_operator.go
  hack/run-upgrade-tests.sh
Labels: approved, lgtm
