Repository openshift-kni/performance-addon-operators, pull requests merged in 2020-11, with the labels that each got.

#427 Small improvements to the generate-index-database script
  README.md
  hack/generate-index-database.sh
Labels: approved, lgtm

#422 [release-4.5] ci: adaptations to operator pipeline
  cluster-setup/ci-upgrade-test-cluster/kustomization.yaml
  cluster-setup/ci-upgrade-test-cluster/performance_profile.yaml
  cluster-setup/mcp-only-cluster/kustomization.yaml
  cluster-setup/mcp-only-cluster/machine_config_pool.yaml
  deploy/metadata/performance-addon-operator/4.4.1/annotations.yaml
  deploy/metadata/performance-addon-operator/4.5.1/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.1/performance-addon-operator.v4.4.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.1/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  hack/run-upgrade-tests.sh
  openshift-ci/Dockerfile.bundle-4.4.ci
  openshift-ci/Dockerfile.bundle.ci
  openshift-ci/Dockerfile.registry.build
  openshift-ci/Dockerfile.registry.upstream.dev
  openshift-ci/Dockerfile.src.ci
Labels: approved, lgtm

#428 Small improvement to the generation of content for the bundle image
  Makefile
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  hack/common.sh
  hack/csv-generate.sh
  hack/generate-metadata.sh
Labels: approved, lgtm

#431 [release-4.5] Move cluster deploy manifests under the performance folder
  cluster-setup/ci-upgrade-test-cluster/performance/kustomization.yaml
  cluster-setup/ci-upgrade-test-cluster/performance/performance_profile.yaml
  cluster-setup/mcp-only-cluster/performance/kustomization.yaml
  cluster-setup/mcp-only-cluster/performance/machine_config_pool.yaml
Labels: approved, lgtm

#425 [release-4.6] Provide dockerfile to generate index.db via opm
  openshift-ci/Dockerfile.index-gen.ci
Labels: approved, lgtm

#429 Remove register image dockerfiles
  .drone.yml
  Makefile
  openshift-ci/Dockerfile.registry.build
  openshift-ci/Dockerfile.registry.intermediate
  openshift-ci/Dockerfile.registry.upstream.dev
Labels: approved, lgtm

#432 Change the index database path to be in sync with CI expectations
  openshift-ci/Dockerfile.index.ci
Labels: approved, lgtm

#430 Remove omitempty from mandatory fields
  api/v2/performanceprofile_types.go
  config/crd/bases/performance.openshift.io_performanceprofiles.yaml
  deploy/olm-catalog/performance-addon-operator/4.7.0/performance.openshift.io_performanceprofiles_crd.yaml
  docs/performance_profile.md
Labels: approved, lgtm

#435 utils: remove dead code
  pkg/controller/performanceprofile/components/utils.go
  pkg/controller/performanceprofile/components/utils_test.go
Labels: approved, lgtm

#424 Add globallyDisableIrqLoadBalancing flag to Performance Profile
  api/v2/performanceprofile_conversion.go
  api/v2/performanceprofile_types.go
  api/v2/zz_generated.deepcopy.go
  build/assets/tuned/openshift-node-performance
  config/crd/bases/performance.openshift.io_performanceprofiles.yaml
  deploy/olm-catalog/performance-addon-operator/4.7.0/performance.openshift.io_performanceprofiles_crd.yaml
  docs/performance_profile.md
  functests/1_performance/performance.go
  functests/2_performance_update/updating_profile.go
  functests/utils/nodes/nodes.go
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/utils.go
  pkg/controller/performanceprofile/components/utils_test.go
Labels: approved, lgtm

#436 must-gather: fix fall-back namespace
  must-gather/collection-scripts/namespace
Labels: approved, lgtm

#433 Use oslat from the cnf-tests image
  functests/4_latency/Dockerfile
  functests/4_latency/latency.go
  functests/4_latency/run-tests.sh
  functests/utils/images/images.go
Labels: approved, lgtm

#434 validate: check for no isolated/reserved cpus
  functests/3_performance_status/status.go
  pkg/controller/performanceprofile/components/profile/profile.go
  pkg/controller/performanceprofile/components/profile/profile_test.go
  pkg/controller/performanceprofile/components/utils.go
  pkg/controller/performanceprofile/components/utils_test.go
Labels: approved, lgtm

#438 add option to set minKubeVersion
  Makefile
  deploy/olm-catalog/performance-addon-operator/4.7.0/performance-addon-operator.v4.7.0.clusterserviceversion.yaml
  hack/common.sh
  hack/csv-generate.sh
  tools/csv-processor/csv-processor.go
Labels: approved, lgtm

#437 Bug 1894861: tests: allow override operator namespace
  cluster-setup/base/performance/operator_namespace.yaml
  cluster-setup/base/performance/operator_operatorgroup.yaml
  cluster-setup/base/performance/operator_subscription.yaml
  cluster-setup/upgrade-test-cluster/performance/operator_subscription.patch.yaml
  config/rbac/role.yaml
  controllers/performanceprofile_controller.go
  functests-extended/1_performance_operator_upgrade/upgrade_operator.go
  functests/utils/consts.go
  functests/utils/namespaces/namespaces.go
  functests/utils/pods/pods.go
  hack/clean-deploy.sh
  hack/run-upgrade-tests.sh
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#439 [release-4.6] Change functest run parameters
  hack/run-functests.sh
Labels: approved, lgtm, ok-to-test

#440 [release-4.5] Change functest run parameters
  hack/run-functests.sh
Labels: approved, lgtm, ok-to-test

#445 Change the user during the registry build
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm

#441 [release-4.4] Change functest run parameters
  hack/run-functests.sh
Labels: approved, lgtm, ok-to-test

#442 Tests: fix default namespace, and allow override
  cluster-setup/base/performance/operator_namespace.yaml
  cluster-setup/base/performance/operator_operatorgroup.yaml
  cluster-setup/base/performance/operator_subscription.yaml
  cluster-setup/upgrade-test-cluster/performance/operator_subscription.patch.yaml
  functests-extended/1_performance_operator_upgrade/upgrade_operator.go
  functests/utils/consts.go
  functests/utils/namespaces/namespaces.go
  functests/utils/pods/pods.go
  hack/clean-deploy.sh
  hack/run-upgrade-tests.sh
Labels: approved, lgtm

#446 csv: csv-processor: don't hardcode annotations
  deploy/olm-catalog/performance-addon-operator/4.7.0/performance-addon-operator.v4.7.0.clusterserviceversion.yaml
  hack/annotations.json
  hack/common.sh
  hack/csv-generate.sh
  tools/csv-processor/csv-processor.go
Labels: approved, lgtm

#447 Fix the tuned profile when IRQ load balancing is not disabled globally
  build/assets/tuned/openshift-node-performance
  functests/2_performance_update/updating_profile.go
Labels: approved, lgtm

#448 Replace tools base image from centos to ubi
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#452 Verify node points to right tuned profile
  functests/1_performance/performance.go
Labels: approved, lgtm, ok-to-test

#450 machineconfig: Set RPS mask for both containers and host
  build/assets/configs/99-low-latency-hooks.json
  build/assets/configs/99-netdev-rps.rules
  build/assets/scripts/low-latency-hooks.sh
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
Labels: approved, lgtm

#456 [release-4.6] Use index image for the dev flow
  .drone.yml
  Makefile
  README.md
  cluster-setup/base/performance/operator_catalogsource.yaml
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  hack/common.sh
  hack/csv-generate.sh
  hack/deploy.sh
  hack/generate-index-database.sh
  hack/generate-manifests-index.sh
  hack/generate-metadata.sh
  openshift-ci/Dockerfile.registry.build
  openshift-ci/Dockerfile.registry.intermediate
  openshift-ci/Dockerfile.registry.upstream.dev
Labels: approved, lgtm

#455 RPS E2E test
  functests/1_performance/performance.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
Labels: approved, lgtm
