Repository openshift-kni/performance-addon-operators, pull requests merged in 2020-03, with the labels that each got.

#113 Updated CI image registry URL
  hack/deploy.sh
  openshift-ci/Dockerfile.registry.build
Labels: approved, size/S

#109 Use k8s cpuset package to convert CPUSet string to list
  functests/performance/cpu_management.go
  functests/performance/topology_manager.go
  go.mod
  go.sum
  pkg/controller/performanceprofile/components/utils.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpuset/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpuset/OWNERS
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpuset/cpuset.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#116 Improve code checks
  Makefile
  hack/csv-generate.sh
  hack/verify-generated.sh
  pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#115 Merge pull request #109 from cynepco3hahue/use_k8s_cpuset
  functests/performance/cpu_management.go
  functests/performance/topology_manager.go
  go.mod
  go.sum
  pkg/controller/performanceprofile/components/utils.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_suite_test.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_test.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpuset/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpuset/OWNERS
  vendor/k8s.io/kubernetes/pkg/kubelet/cm/cpuset/cpuset.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#112 [release-4.4] Pin registry image to version 4.4
  openshift-ci/Dockerfile.registry.build
  openshift-ci/Dockerfile.registry.intermediate
  openshift-ci/Dockerfile.registry.upstream.dev
Labels: approved, lgtm, size/XS

#104 Reboot from rpm-ostree injection in pre-boot
  build/assets/scripts/pre-boot-tuning.sh
  build/assets/scripts/reboot.sh
  functests/performance/performance.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
Labels: approved, lgtm, size/M

#121 Revert CI registry URL
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm, size/XS

#111 Pin registry image to version 4.5
  openshift-ci/Dockerfile.registry.build
  openshift-ci/Dockerfile.registry.intermediate
  openshift-ci/Dockerfile.registry.upstream.dev
Labels: approved, lgtm, size/XS

#119 Finalize tuning parameters and values
  build/assets/scripts/pre-boot-tuning.sh
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
Labels: approved, lgtm, size/S

#123 Fixed KubeletConfig
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig.go
Labels: approved, lgtm, size/XS

#130 Revert "[release-4.4] Reboot from rpm-ostree injection in pre-boot"
  build/assets/scripts/pre-boot-tuning.sh
  build/assets/scripts/reboot.sh
  functests/performance/performance.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
Labels: approved, lgtm, size/M

#117 Add options to configure KubeletConfig via PerformanceProfile CR
  cluster-setup/base/performance/performance_profile.yaml
  deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml
  functests/performance/topology_manager.go
  pkg/apis/performance/v1alpha1/performanceprofile_types.go
  pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig_test.go
  pkg/controller/performanceprofile/components/profile/profile.go
  pkg/utils/testing/testing.go
Labels: approved, lgtm, ok-to-test, size/L

#131 [release-4.4] Add injection check for rpm-ostree
  build/assets/scripts/pre-boot-tuning.sh
Labels: approved, lgtm, size/XS

#132 Sync with release-4.4
  build/assets/scripts/pre-boot-tuning.sh
  build/assets/scripts/reboot.sh
  functests/performance/performance.go
  hack/wait-for-mcp.sh
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
Labels: approved, lgtm, size/M

#134 Temporarily disable RT kernel
  cluster-setup/ci-cluster/performance/performance_profile.patch.yaml
Labels: approved, lgtm, size/XS

#133 Add additional kerenel arguments option in CRD
  cluster-setup/ci-cluster/performance/performance_profile.patch.yaml
  deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/crds/performance.openshift.io_v1alpha1_performanceprofile_cr.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance-addon-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml
  functests/performance/performance.go
  pkg/apis/performance/v1alpha1/performanceprofile_types.go
  pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
Labels: approved, lgtm, size/L

#135 [release-4.4] Add additional kerenel arguments option in CRD
  cluster-setup/ci-cluster/performance/performance_profile.patch.yaml
  deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/crds/performance.openshift.io_v1alpha1_performanceprofile_cr.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance-addon-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml
  functests/performance/performance.go
  pkg/apis/performance/v1alpha1/performanceprofile_types.go
  pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
Labels: approved, lgtm, size/L

#136 Revert "Temporarily disable RT kernel"
  cluster-setup/ci-cluster/performance/performance_profile.patch.yaml
Labels: approved, lgtm, size/XS

#137 Be less verbose, decrease wait times
  hack/deploy.sh
  hack/wait-for-mcp.sh
Labels: approved, lgtm, size/M

#124 Add test case id's to tests
  functests/performance/cpu_management.go
  functests/performance/hugepages.go
  functests/performance/performance.go
  functests/performance/rt-kernel.go
  functests/performance/topology_manager.go
Labels: approved, lgtm, ok-to-test, size/M

#138 fix guaranteed and cpu affinity tests
  functests/performance/cpu_management.go
Labels: approved, lgtm, ok-to-test, size/S

#139 tools: add a simpler tool to update the image ref
  .gitignore
  Makefile
  pkg/utils/csvtools/csvtools.go
  tools/csv-generator/csv-generator.go
  tools/csv-replace-imageref/csv-replace-imageref.go
Labels: approved, lgtm, size/L

#143 Add verification to the hugepages allocation script
  build/assets/scripts/hugepages-allocation.sh
Labels: approved, lgtm

#142 make topology manager func test more flexible
  functests/performance/topology_manager.go
Labels: approved, lgtm, ok-to-test

#127 Add functional tests - updating performance profile
  functests/performance/updating_profile.go
  hack/run-functests.sh
Labels: approved, lgtm, ok-to-test, size/L

#145 add functional test: changing nodeSelector in performance profile
  functests/performance/updating_profile.go
Labels: approved, lgtm, ok-to-test

#144 Merge network and realtime profile to one profile
  build/assets/tuned/openshift-node-performance
  build/assets/tuned/openshift-node-real-time-kernel
  functests/performance/performance.go
  pkg/controller/performanceprofile/components/consts.go
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
  pkg/controller/performanceprofile/performanceprofile_controller.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
Labels: approved, lgtm

#147 [release-4.4] Add functional tests - updating performance profile
  functests/performance/updating_profile.go
  hack/run-functests.sh
Labels: approved, lgtm

#149 Fix performance test for merged profile
  functests/performance/performance.go
Labels: approved, lgtm

#150 Test RT Kernel not installed on non worker-rt node
  functests/performance/rt-kernel.go
  functests/utils/consts.go
  functests/utils/nodes/nodes.go
Labels: approved, lgtm, ok-to-test

#153 Add Polarion reporter
  functests/test_suite_test.go
  go.mod
  go.sum
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: approved, lgtm

#155 clean-deploy.sh gets labels and mcp from performanceprofile settings
  hack/clean-deploy.sh
Labels: approved, lgtm

#156 fix OC_CLIENT in clean-deploy.sh
  hack/clean-deploy.sh
Labels: approved, lgtm
