Repository openshift-kni/performance-addon-operators, pull requests merged in 2020-10, with the labels that each got.

#371 [release-4.4] Fix for cpu affinity test
  functests/performance/cpu_management.go
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm

#385 Provide manifests and script to run upgrade test under the CI
  Makefile
  cluster-setup/ci-upgrade-test-cluster/performance/kustomization.yaml
  cluster-setup/ci-upgrade-test-cluster/performance/performance_profile.yaml
  hack/ci-run-upgrade-test.sh
Labels: approved, lgtm

#386 e2e: fix the runtime class test
  functests/1_performance/cpu_management.go
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm

#387 [release-4.6] ci: adaptations to operator pipeline
  cluster-setup/ci-upgrade-test-cluster/performance/kustomization.yaml
  cluster-setup/ci-upgrade-test-cluster/performance/performance_profile.yaml
  cluster-setup/mcp-only-cluster/performance/kustomization.yaml
  cluster-setup/mcp-only-cluster/performance/machine_config_pool.yaml
  deploy/metadata/performance-addon-operator/4.5.1/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.1/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  hack/run-upgrade-tests.sh
  openshift-ci/Dockerfile.bundle-4.5.ci
Labels: approved, lgtm

#388 ci: remove unneeded ci-upgrade-test script
  Makefile
  hack/ci-run-upgrade-test.sh
  hack/run-upgrade-tests.sh
Labels: approved, lgtm

#389 csv: add more annotations
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml
Labels: approved, lgtm

#390 Fix for upgrade script: make deploying PAO optional
  hack/run-upgrade-tests.sh
Labels: approved, lgtm

#391 e2e: fix getting a profile by the node selector
  functests/utils/profiles/profiles.go
Labels: approved, lgtm

#394 functests: don't read stderr when getting logs
  functests/utils/utils.go
Labels: approved, lgtm

#397 latency-test: add and pass initial delay
  README.md
  functests/4_latency/latency.go
Labels: approved, lgtm

#378 controller: validation: check for cpu cores split
  functests/3_performance_status/status.go
  functests/utils/profiles/profiles.go
  pkg/controller/performanceprofile/components/profile/profile.go
  pkg/controller/performanceprofile/components/profile/profile_test.go
  pkg/controller/performanceprofile/components/utils.go
  pkg/controller/performanceprofile/components/utils_test.go
Labels: approved, lgtm

#400 e2e: fix runtime class test failures
  functests/1_performance/cpu_management.go
Labels: approved, lgtm

#401 config: Remove auto-generated templates
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_performanceprofiles.yaml
  config/crd/patches/webhook_in_performanceprofiles.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/performanceprofile_editor_role.yaml
  config/rbac/performanceprofile_viewer_role.yaml
  config/scorecard/bases/config.yaml
  config/scorecard/kustomization.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/service.yaml
Labels: approved, lgtm

#408 Fix for test - MCP status in performance profile
  functests/3_performance_status/status.go
Labels: approved, lgtm

#407 Fix typo, and x.y / y.z discrepancies in README.md
  README.md
Labels: approved, lgtm, ok-to-test

#405 Fix for update test - make verification of cpu affinity mask flexible
  functests/2_performance_update/updating_profile.go
Labels: approved, lgtm

#406 docs: Add API versions support doc
  README.md
  docs/api-versions.md
Labels: approved, lgtm

#411 [release-4.6] Fix for test - MCP status in performance profile
  functests/3_performance_status/status.go
Labels: approved, lgtm

#414 Provide the Dockerfile to generate index database under the CI
  openshift-ci/Dockerfile.index-gen.ci
  openshift-ci/Dockerfile.index.ci
Labels: approved, lgtm

#412 Bug 1889633: Fix for test: hugepages with NUMA node
  functests/1_performance/hugepages.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#417 e2e: fix conversion test
  functests/1_performance/performance.go
Labels: approved, lgtm

#416 e2e: check that it no error before accessing the profile fields
  functests/1_performance/cpu_management.go
Labels: approved, lgtm

#421 deploy: Rollback the 4.6 CSV and CRD to before the webhook conversion
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance.openshift.io_performanceprofiles_crd.yaml
Labels: approved, lgtm

#410 Use index image for the dev flow
  Makefile
  cluster-setup/base/performance/operator_catalogsource.yaml
  hack/common.sh
  hack/deploy.sh
  hack/generate-index-database.sh
  hack/generate-manifests-index.sh
Labels: approved, lgtm

#423 Change functest run parameters
  hack/run-functests.sh
Labels: approved, lgtm
