Repository openshift-kni/performance-addon-operators, pull requests merged in 2020-04, with the labels that each got.

#162 Fix CI registry URL
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm

#159 [release-4.4] Add Polarion reporter
  functests/test_suite_test.go
  go.mod
  go.sum
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: approved, lgtm

#164 Fix CI (several issues)
  functests/performance/performance.go
  functests/performance/topology_manager.go
  functests/utils/nodes/nodes.go
  functests/utils/pods/pods.go
  hack/deploy.sh
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm

#157 Improved docs
  CONTRIBUTING.md
  Makefile
  README.md
  docs/performance_profile.md
  docs/troubleshooting.md
  hack/docs-generate.sh
  tools/docs-generator/docs-generator.go
Labels: approved, lgtm

#158 Divide updating profile tests for better interraction with polarion
  functests/performance/updating_profile.go
  functests/utils/utils.go
Labels: approved, lgtm

#166 Add missing hashes to go.sum
  go.sum
Labels: approved, lgtm

#161 Ensure non-RT Kernel installed when realTimeKernel is false
  functests/performance/updating_profile.go
  functests/utils/profiles/profiles.go
Labels: approved, lgtm, ok-to-test

#154 Add Informational status reporting on Performance Profile CR against Machine config pools
  pkg/controller/performanceprofile/performanceprofile_controller.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
  pkg/controller/performanceprofile/status.go
Labels: approved, lgtm

#167 Updating qe-tool
  go.mod
  go.sum
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/modules.txt
Labels: approved, lgtm

#168 Added test - removing rt label
  functests/performance/performance.go
  functests/performance/updating_profile.go
  functests/utils/consts.go
Labels: approved, lgtm

#171 [release-4.4] Backport CI registry URL fix
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm

#169 [release-4.4] Updating qe-tools to v0.1.6
  go.mod
  go.sum
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/modules.txt
Labels: approved, lgtm

#177 Change CI registry URL and fix oc wait
  hack/clean-deploy.sh
  hack/wait-for-mcp.sh
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm

#180 back to old CI cluster...?
  openshift-ci/Dockerfile.registry.build
Labels: approved

#179 Fix for nodeSelector test
  functests/performance/updating_profile.go
Labels: approved, lgtm

#178 Restore performance profile parameters after running tests
  functests/performance/updating_profile.go
Labels: approved, lgtm

#182 Increase MCP update timeout
  hack/wait-for-mcp.sh
Labels: approved, lgtm

#173 Update NTO dependencies against oc 4.5
  go.mod
  go.sum
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/tuned_types.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/zz_generated.deepcopy.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/OWNERS
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
  vendor/sigs.k8s.io/yaml/yaml.go
Labels: approved, lgtm

#165 tests: better logs
  functests/performance/performance.go
  functests/utils/nodes/nodes.go
Labels: approved, lgtm

#174 Clarify default values of RT kernel config
  deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml
  docs/performance_profile.md
  pkg/apis/performance/v1alpha1/performanceprofile_types.go
  tools/docs-generator/docs-generator.go
Labels: approved, lgtm

#175 csv-generator: add option to read description
  tools/csv-generator/csv-generator.go
Labels: approved, lgtm

#176 Add missing performance tags.
  functests/performance/performance.go
  functests/performance/updating_profile.go
Labels: approved, lgtm

#186 Better logs for command executions
  functests/performance/cpu_management.go
  functests/performance/hugepages.go
  functests/performance/performance.go
  functests/performance/topology_manager.go
  functests/utils/nodes/nodes.go
  functests/utils/pods/pods.go
  functests/utils/utils.go
Labels: approved, lgtm

#184 Remove nohz_full from kargs
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
Labels: approved, lgtm

#187 Add support for running tests in a disconnected environment.
  functests/1_performance/cpu_management.go
  functests/1_performance/hugepages.go
  functests/1_performance/rt-kernel.go
  functests/1_performance/topology_manager.go
  functests/utils/images/images.go
  functests/utils/pods/pods.go
Labels: approved, lgtm

#185 Removing leftovers after running nodeSelector and label removing tests
  functests/2_performance_update/updating_profile.go
Labels: approved, lgtm

#170 RT Kernel is not installed when PerformanceProfile has no realTimeKernel field
  functests/2_performance_update/updating_profile.go
Labels: approved, lgtm, ok-to-test

#191 Fixed minor typo
  README.md
Labels: approved, lgtm

#194 Retry getting MCP
  functests/utils/client/clients.go
  functests/utils/mcps/mcps.go
Labels: approved, lgtm

#192 Use test images mirrored on openshift-kni org.
  functests/1_performance/cpu_management.go
  functests/utils/images/images.go
Labels: approved, lgtm

#193 Fix for manual profile and cleaning script
  cluster-setup/manual-cluster/performance/performance_profile.yaml
  hack/clean-deploy.sh
Labels: approved, lgtm

#195 Don't exit if the client configuration is not valid.
  functests/0_config/test_suite_performance_config_test.go
  functests/1_performance/test_suite_performance_test.go
  functests/2_performance_update/test_suite_performance_update_test.go
  functests/utils/client/clients.go
Labels: approved, lgtm

#196 Implement release process
  .drone.yml
  .gitignore
  Makefile
  build/Dockerfile
  cluster-setup/base/performance/operator_subscription.yaml
  deploy/Dockerfile
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  docs/releasing.md
  hack/csv-generate.sh
  hack/generate-release-tags.sh
  hack/release-note.sh
  openshift-ci/Dockerfile.deploy
  openshift-ci/Dockerfile.registry.upstream.dev
Labels: approved, lgtm

#199 Delete SR-IOV test
  functests/1_performance/topology_manager.go
  functests/utils/nodes/nodes.go
Labels: approved, lgtm
