Repository openshift-kni/performance-addon-operators, pull requests merged in 2020-09, with the labels that each got.

#330 Bug 1872417: E2e tests - do not panic in discovery mode with no profile installed.
  functests/1_performance/cpu_management.go
  functests/1_performance/hugepages.go
  functests/1_performance/performance.go
  functests/1_performance/rt-kernel.go
  functests/1_performance/topology_manager.go
  functests/2_performance_update/updating_profile.go
  functests/3_performance_status/status.go
  functests/4_latency/latency.go
  functests/utils/consts.go
  functests/utils/discovery/discovery.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#331 Added test that verifies rcu_nocbs kernel argument on the node
  functests/1_performance/cpu_management.go
Labels: approved, lgtm

#335 Adding readability for the latency test
  functests/4_latency/latency.go
Labels: approved, lgtm, ok-to-test

#336 Removed duplicated imports in tests
  functests/1_performance/hugepages.go
  functests/1_performance/performance.go
  functests/1_performance/topology_manager.go
  functests/2_performance_update/updating_profile.go
  functests/3_performance_status/status.go
  functests/4_latency/latency.go
Labels: approved, lgtm

#337 Fix CPU managment test to check for right numbers of isolated CPUs
  functests/1_performance/cpu_management.go
Labels: approved, lgtm

#338 Fix generate scripts to support generation of z-stream manifests
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance.openshift.io_performanceprofiles_crd.yaml
  hack/csv-generate.sh
  hack/generate-manifests-index.sh
  hack/generate-manifests-tree.sh
Labels: approved, lgtm

#344 release-4.5: prepare CSV for 4.5.1 z-stream release
  cluster-setup/base/performance/operator_subscription.yaml
  cluster-setup/upgrade-test-cluster/performance/operator_subscription.patch.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.1/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  hack/csv-generate.sh
  hack/run-upgrade-tests.sh
Labels: approved, lgtm

#345 e2e tests: fix the RT kernel check
  functests/utils/nodes/nodes.go
Labels: approved, lgtm

#347 release-4.4: prepare 4.4.1 CSV manifests
  Makefile
  cluster-setup/base/performance/operator_subscription.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.0/performance-addon-operator.v4.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.0/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.1/performance-addon-operator.v4.4.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.1/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  hack/csv-generate.sh
Labels: approved, lgtm

#346 Update CSV and package
  README.md
  cluster-setup/base/performance/operator_subscription.yaml
  cluster-setup/upgrade-test-cluster/performance/operator_subscription.patch.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  hack/csv-generate.sh
  hack/run-upgrade-tests.sh
Labels: approved, lgtm

#349 Update package yaml to point to 4.4.1 CSV
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
Labels: approved, lgtm

#350 Remove bitbucket.org/ww/goautoneg dependency
  go.mod
  go.sum
Labels: approved, lgtm

#354 [release-4.5] Remove bitbucket.org/ww/goautoneg dependency
  go.mod
  go.sum
Labels: approved, lgtm

#340 Enable support for stall daemon in base profile
  build/assets/tuned/openshift-node-performance
  functests/1_performance/performance.go
Labels: approved, lgtm

#356 Change the registry
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm

#361 Adapt our Dockerfiles to build operator under the CI
  deploy/metadata/performance-addon-operator/4.6.0/annotations.yaml
  openshift-ci/Dockerfile.bundle.ci
  openshift-ci/Dockerfile.src.ci
Labels: approved, lgtm

#362 Fix for CPU Affinity mask test
  functests/1_performance/cpu_management.go
Labels: approved, lgtm

#357 Set Tuned created CR to higher priority
  pkg/controller/performanceprofile/components/tuned/tuned.go
Labels: approved, lgtm

#358 must-gather: fix container image lookup
  must-gather/collection-scripts/gather_nodes
  must-gather/collection-scripts/namespace
Labels: approved, lgtm

#369 Do not run 2_performance_update test suit
  hack/run-functests.sh
Labels: approved, lgtm

#366 Update the metadata with 4.6 channel
  deploy/metadata/performance-addon-operator/4.6.0/annotations.yaml
Labels: approved, lgtm

#373 Pao run master nodes
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  functests/1_performance/performance.go
  functests/utils/consts.go
  functests/utils/pods/pods.go
Labels: approved, lgtm

#375 functests: ensure deleted objects are really gone
  functests/1_performance/cpu_management.go
  functests/1_performance/performance.go
  functests/4_latency/latency.go
  functests/utils/clean/clean.go
  functests/utils/profiles/profiles.go
Labels: approved, lgtm

#379 Adaptation to build operators under the OpenShift CI
  cluster-setup/mcp-only-cluster/performance/kustomization.yaml
  cluster-setup/mcp-only-cluster/performance/machine_config_pool.yaml
  deploy/metadata/performance-addon-operator/4.5.1/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.1/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  openshift-ci/Dockerfile.bundle-4.5.ci
Labels: approved, lgtm

#380 Add a loop to the hugepages allocation script
  build/assets/scripts/hugepages-allocation.sh
Labels: approved, lgtm

#384 Update owners aliases
  OWNERS_ALIASES
Labels: approved, lgtm

#381 Point 4.5 CSVs to the 4.5-snapshot
  deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml
Labels: approved, lgtm
