Repository openshift-kni/performance-addon-operators, pull requests merged in 2020-12, with the labels that each got.

#457 Promote kubelet config errors
  controllers/performanceprofile_controller.go
  controllers/performanceprofile_controller_test.go
  controllers/status.go
Labels: approved, lgtm

#459 Align CPU load balancing functionality with the latest CRI-O changes
  build/assets/configs/99-runtimes.conf
  controllers/performanceprofile_controller.go
  controllers/performanceprofile_controller_test.go
  docs/cpu-load-balancing.md
  functests/1_performance/cpu_management.go
  functests/1_performance/performance.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
Labels: approved, lgtm

#460 docs: Add irq-load-balancing documentation
  docs/api-versions.md
  docs/irq-load-balancing.md
Labels: approved, lgtm

#458 Fail the upgrade test when the cluster deploy failed
  hack/run-upgrade-tests.sh
Labels: approved, lgtm

#465 release-4.5: prepare CSV for 4.5.2 z-stream release
  deploy/olm-catalog/performance-addon-operator/4.5.2/performance-addon-operator.v4.5.2.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.2/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  hack/csv-generate.sh
Labels: approved, lgtm

#466 machineconfig: fix the RPS boot failures
  build/assets/scripts/set-rps-mask.sh
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
Labels: approved, lgtm

#469 Fix CI upgrade test
  cluster-setup/ci-upgrade-test-cluster/performance/performance_profile.yaml
Labels: approved, lgtm

#470 Revert the change of the generated runtime class name
  build/assets/configs/99-runtimes.conf
  controllers/performanceprofile_controller.go
  controllers/performanceprofile_controller_test.go
  functests/1_performance/performance.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
Labels: approved, lgtm

#462 Bug 1905492: Update the tuned profile to set higher scheduler priority
  build/assets/tuned/openshift-node-performance
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#451 Add test verifying that IRQ balance can be disabled per POD
  functests/1_performance/cpu_management.go
  functests/2_performance_update/updating_profile.go
  functests/utils/nodes/nodes.go
Labels: approved, lgtm

#473 scripts: Yet another improvement to the set-rps-mask.sh script
  build/assets/scripts/set-rps-mask.sh
Labels: approved, lgtm

#471 docs: Add a debugging section to the IRQ load balancing doc.
  docs/irq-load-balancing.md
Labels: approved, lgtm

#472 e2e: fix nil pointer errors during dereference of the enable field
  functests/1_performance/performance.go
  functests/1_performance/rt-kernel.go
Labels: approved, lgtm

#475 Remove Duplicate Polarion test case id:
  functests/1_performance/cpu_management.go
Labels: approved, lgtm, ok-to-test

#476 e2e: increase the pod deletion timeout
  functests/1_performance/cpu_management.go
  functests/1_performance/hugepages.go
  functests/4_latency/latency.go
  functests/utils/pods/pods.go
Labels: approved, lgtm

#474 e2e: timeout command execution after two minutes
  functests/utils/utils.go
Labels: approved, lgtm

#478 Bug 1899411: include the API version under the CSV owned CRDs
  deploy/olm-catalog/performance-addon-operator/4.7.0/performance-addon-operator.v4.7.0.clusterserviceversion.yaml
  tools/csv-processor/csv-processor.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#477 e2e: fetch sched_domains for all CPUs to validate CPU load balance disabling
  functests/1_performance/cpu_management.go
Labels: approved, lgtm
