Repository openshift-kni/performance-addon-operators, pull requests merged in 2020-01, with the labels that each got.

#24 Codify performance manifests
  Makefile
  build/Dockerfile
  build/assets/scripts/pre-boot-tuning.sh
  build/assets/scripts/reboot.sh
  build/assets/scripts/rt-kernel.sh
  build/assets/tuned/openshift-node-network-latency
  build/assets/tuned/openshift-node-real-time-kernel
  deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml
  go.mod
  go.sum
  pkg/apis/performance/v1alpha1/performanceprofile_types.go
  pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/performanceprofile/components/consts.go
  pkg/controller/performanceprofile/components/featuregate/featuregate.go
  pkg/controller/performanceprofile/components/featuregate/featuregate_suite_test.go
  pkg/controller/performanceprofile/components/featuregate/featuregate_test.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig_suite_test.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig_test.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_suite_test.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/controller/performanceprofile/components/machineconfigpool/machineconfigpool.go
  pkg/controller/performanceprofile/components/machineconfigpool/machineconfigpool_suite_test.go
  pkg/controller/performanceprofile/components/machineconfigpool/machineconfigpool_test.go
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_suite_test.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
  pkg/controller/performanceprofile/components/utils.go
  pkg/utils/testing/testing.go
  vendor/github.com/openshift/cluster-node-tuning-operator/LICENSE
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/register.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/doc.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/register.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/tuned_types.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/doc.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go
  vendor/k8s.io/utils/pointer/OWNERS
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#27 Deploy performance components under CI
  Makefile
  cluster-setup/base/performance/kustomization.yaml
  cluster-setup/base/performance/performance_profile.yaml
  cluster-setup/ci-cluster/performance/kustomization.yaml
  cluster-setup/ci-cluster/performance/performance_profile.patch.yaml
  functests/test_suite_test.go
  functests/utils/consts.go
  functests/utils/machineconfigpool/machineconfigpool.go
  hack/clean-deploy.sh
  hack/deploy.sh
  openshift-ci/Dockerfile.deploy
Labels: approved, lgtm, size/L

#34 Install RT kernel from RPMs included in RHCOS
  Makefile
  build/assets/scripts/rt-kernel.sh
  cluster-setup/base/performance/performance_profile.yaml
  deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operators/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml
  functests/performance/rt-kernel.go
  functests/utils/pods/pods.go
  hack/label-worker-rt.sh
  pkg/apis/performance/v1alpha1/performanceprofile_types.go
  pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/controller/performanceprofile/performanceprofile_controller.go
  pkg/utils/testing/testing.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#31 Force latency is not supported with cstate in tuned 2.11
  build/assets/tuned/openshift-node-network-latency
Labels: approved, lgtm, size/XS

#36 Expose status under performance profile resource
  deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operators/0.0.1/performance-addon-operators.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operators/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/performance/v1alpha1/performanceprofile_types.go
  pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/performanceprofile/performanceprofile_controller.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
  pkg/controller/performanceprofile/status.go
  vendor/github.com/openshift/custom-resource-status/LICENSE
  vendor/github.com/openshift/custom-resource-status/conditions/v1/_doc.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/conditions.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/types.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/zz_generated.deepcopy.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#13 Updated CONTRIBUTOR guidelines
  CONTRIBUTING.md
Labels: approved, lgtm, size/M

#38 makefile: add a target to only build the binary
  Makefile
Labels: approved, lgtm, size/XS

#37 Performance e2e Tests
  functests/performance/performance.go
  functests/utils/client/clients.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/typed/tuned/v1/doc.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/typed/tuned/v1/generated_expansion.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/typed/tuned/v1/profile.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/typed/tuned/v1/tuned.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/generated/clientset/versioned/typed/tuned/v1/tuned_client.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#39 Add events to the performance profile controller
  pkg/controller/performanceprofile/performanceprofile_controller.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
Labels: approved, lgtm, size/M

#43 Fix 'make govet' make target
  Makefile
  go.mod
  go.sum
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#41 metadata: olm: rename operatorS -> operator in metadata
  CONTRIBUTING.md
  Makefile
  deploy/Dockerfile
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance-addon-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  deploy/olm-catalog/performance-addon-operators/performance-addon-operators.package.yaml
  hack/clean-deploy.sh
  hack/deploy.sh
  openshift-ci/Dockerfile.deploy
  openshift-ci/Dockerfile.registry.build
Labels: approved, lgtm, size/M

#40 Removed creation of MCP by operator
  CONTRIBUTING.md
  Makefile
  README.md
  cluster-setup/base/feature_sctp/kustomization.yaml
  cluster-setup/base/feature_sctp/sctp_module_mc.yaml
  cluster-setup/base/performance/kustomization.yaml
  cluster-setup/base/performance/operator_catalogsource.yaml
  cluster-setup/base/performance/operator_namespace.yaml
  cluster-setup/base/performance/operator_operatorgroup.yaml
  cluster-setup/base/performance/operator_subscription.yaml
  cluster-setup/ci-cluster/feature_sctp/kustomization.yaml
  cluster-setup/ci-cluster/feature_sctp/sctp_module_mc.patch.yaml
  cluster-setup/ci-cluster/feature_sctp/wait_for_it.sh
  cluster-setup/ci-cluster/performance/kustomization.yaml
  cluster-setup/ci-cluster/performance/machine_config_pool.yaml
  deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml
  functests/test_suite_test.go
  hack/deploy.sh
  hack/label-worker-rt.sh
  hack/setup_test_cluster.sh
  hack/verify-generated.sh
  hack/wait-for-mcp.sh
  pkg/apis/performance/v1alpha1/performanceprofile_types.go
  pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/performanceprofile/components/consts.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig_test.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/controller/performanceprofile/components/machineconfigpool/machineconfigpool.go
  pkg/controller/performanceprofile/components/machineconfigpool/machineconfigpool_test.go
  pkg/controller/performanceprofile/components/profile/profile.go
  pkg/controller/performanceprofile/components/profile/profile_suite_test.go
  pkg/controller/performanceprofile/components/profile/profile_test.go
  pkg/controller/performanceprofile/components/utils.go
  pkg/controller/performanceprofile/performanceprofile_controller.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
  pkg/controller/performanceprofile/resources.go
  pkg/controller/performanceprofile/status.go
  pkg/utils/testing/testing.go
Labels: approved, lgtm, size/XXL

#44 Add ability to "pause" a performance profile's reconcile loop
  pkg/apis/performance/v1alpha1/performanceprofile_types.go
  pkg/controller/performanceprofile/components/profile/profile.go
  pkg/controller/performanceprofile/performanceprofile_controller.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
Labels: approved, lgtm, size/M

#45 Adds dockerfile for building and promoting upstream dev public images
  openshift-ci/Dockerfile.registry.upstream.dev
Labels: approved, lgtm, size/S

#46 Make it possible to run tests against an external cluster
  Makefile
  functests/performance/performance.go
  functests/utils/consts.go
  hack/run-functests.sh
Labels: approved, lgtm, size/M

#47 Remove RT kernel workaround and use new MC config instead
  Makefile
  build/assets/scripts/rt-kernel.sh
  functests/performance/performance.go
  go.mod
  go.sum
  hack/wait-for-mcp.sh
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/helpers.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1/types.go
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#51 Install go via gimme
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/S

#49 Exclusively select worker node
  hack/label-worker-rt.sh
Labels: approved, lgtm, ok-to-test, size/XS

#52 point our upstream images to the openshift-kni quay.io org
  openshift-ci/Dockerfile.registry.upstream.dev
Labels: approved, lgtm, size/XS

#58 Fix csv dir permissions
  tools/csv-generator/csv-generator.go
Labels: approved, lgtm, size/XS

#59 Try to make glcoud client happy with python2
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/XS

#54 Echo retries left
  hack/wait-for-mcp.sh
Labels: approved, lgtm, ok-to-test, size/XS

#57 Replaced "kustomize" with "oc kustomize"
  Makefile
  cluster-setup/base/performance/kustomization.yaml
  cluster-setup/base/performance/machine_config_pool.yaml
  cluster-setup/ci-cluster/performance/kustomization.yaml
  hack/clean-deploy.sh
  hack/deploy.sh
  hack/label-worker-rt.sh
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm, size/M

#61 Revert back force_latency to use cstate
  build/assets/tuned/openshift-node-network-latency
Labels: approved, lgtm, size/XS

#55 Don't ignore existing image vars
  Makefile
Labels: approved, lgtm, size/XS
