Repository openshift-kni/performance-addon-operators, pull requests merged in 2021-01, with the labels that each got.

#481 Bug 1912118: does not set RT parameters for non-RT kernel
  build/assets/tuned/openshift-node-performance
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#483 must-gather: dockerfile: rebase on 4.7.0
  openshift-ci/Dockerfile.must-gather
Labels: approved, lgtm

#464 bug 1906355 must-gather: wait when gathering node logs
  must-gather/collection-scripts/gather_nodes
Labels: approved, lgtm

#482 Merge pull request #481 from cynepco3hahue/disable_rt_parameter
  build/assets/tuned/openshift-node-performance
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
Labels: approved, do-not-merge/hold, lgtm

#463 Make test "tuned profile validation" more flexible
  functests/1_performance/performance.go
Labels: approved, lgtm

#479 Bug 1903820: watch machine config pools not owned by the performance profile
  controllers/performanceprofile_controller.go
  controllers/performanceprofile_controller_test.go
  controllers/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#491 e2e: fix nil pointer under the conversion test
  functests/1_performance/performance.go
Labels: approved, lgtm

#492 Revert the remove of duplicate MCP entries
  controllers/status.go
Labels: approved, lgtm

#486 Revert: does not set RT parameters for non-RT kernel
  build/assets/tuned/openshift-node-performance
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
Labels: approved, lgtm

#496 docs: Add a note about PAO supporting only AllNamespaces InstallModeType
  README.md
Labels: approved, lgtm

#454 Don't check for errors while waiting for profile to be applied.
  functests/0_config/config.go
  functests/utils/clean/clean.go
  functests/utils/mcps/mcps.go
  go.mod
  pkg/controller/performanceprofile/components/consts.go
Labels: approved, lgtm

#493 must-gather: compress kubelet logs
  must-gather/collection-scripts/gather_nodes
Labels: approved, lgtm

#485 Revert "Merge pull request #481 from cynepco3hahue/disable_rt_parameter"
  build/assets/tuned/openshift-node-performance
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
Labels: approved, lgtm

#480 e2e: enable back update tests
  functests-extended/1_performance_operator_upgrade/upgrade_operator.go
  functests/0_config/config.go
  functests/2_performance_update/updating_profile.go
  functests/utils/mcps/mcps.go
  functests/utils/profiles/profiles.go
  hack/run-functests.sh
Labels: approved, lgtm

#498 deploy: docker: prepare 4.8 manifests
  deploy/metadata/performance-addon-operator/4.8.0/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance.openshift.io_performanceprofiles_crd.yaml
  openshift-ci/Dockerfile.bundle-4.7.ci
Labels: approved, lgtm

#497 prepare for branch 4.8.0
  Makefile
  cluster-setup/base/performance/operator_subscription.yaml
  deploy/olm-catalog/performance-addon-operator/4.7.0/performance-addon-operator.v4.7.0.clusterserviceversion.yaml
  hack/common.sh
  hack/csv-generate.sh
  hack/generate-index-database.sh
  hack/run-upgrade-tests.sh
  openshift-ci/Dockerfile.bundle.ci
  openshift-ci/Dockerfile.bundle.upstream.dev
Labels: approved, lgtm

#501 Configure CRI-O infra containers CPUs
  build/assets/configs/99-runtimes.conf
  functests/1_performance/cpu_management.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
Labels: approved, lgtm

#502 CSV: add icon
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml
  docs/pao-icon.svg
  hack/csv-generate.sh
  tools/csv-processor/csv-processor.go
Labels: approved, lgtm

#503 [release-4.7] CSV: add icon
  deploy/olm-catalog/performance-addon-operator/4.7.0/performance-addon-operator.v4.7.0.clusterserviceversion.yaml
  docs/pao-icon.svg
  hack/csv-generate.sh
  tools/csv-processor/csv-processor.go
Labels: approved, lgtm

#505 tools: add gather-sysinfo helper
  Makefile
  go.mod
  go.sum
  tools/gather-sysinfo/gather-sysinfo.go
  vendor/github.com/jaypipes/ghw/COPYING
  vendor/github.com/jaypipes/ghw/pkg/option/option.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_block.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/pack.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/testdata.tar.gz
  vendor/github.com/jaypipes/ghw/pkg/snapshot/trace.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/unpack.go
  vendor/modules.txt
Labels: approved, lgtm

#506 must-gather: doc: fix README
  must-gather/README.md
Labels: approved, lgtm

#494 snapshot sysfs/procfs inside must-gather
  must-gather/collection-scripts/gather_nodes
  openshift-ci/Dockerfile.must-gather
  tools/gather-sysinfo/gather-sysinfo.go
Labels: approved, lgtm

#507 must-gather: narrow down permissions
  must-gather/node-gather/daemonset.yaml
Labels: approved, lgtm

#511 Skeleton code for the performance profile creator tool
  Makefile
  cmd/performance-profile-creator/cmd/root.go
  cmd/performance-profile-creator/main.go
  go.mod
  go.sum
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/CHANGELOG.md
  vendor/github.com/spf13/cobra/CONTRIBUTING.md
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/custom_completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/fish_completions.md
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/modules.txt
Labels: approved, lgtm

#513 Makefile: build the profile helper by default
  Makefile
Labels: approved, lgtm

#509 Bug 1921039: [release-4.6] CSV: add icon
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml
  docs/pao-icon.svg
  hack/csv-generate.sh
  tools/csv-generator/csv-generator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#515 Add performance-profile-creator binary to the PAO Dockerfile
  openshift-ci/Dockerfile.deploy
Labels: approved, lgtm

#516 release: prepare for 4.6.1
  deploy/metadata/performance-addon-operator/4.6.1/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.1/performance-addon-operator.v4.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.1/performance.openshift.io_performanceprofiles_crd.yaml
  hack/common.sh
  hack/generate-release-tags.sh
  openshift-ci/Dockerfile.bundle.ci
  openshift-ci/Dockerfile.bundle.upstream.dev
Labels: approved, lgtm

#517 Performance Profile Creator Documentation
  cmd/performance-profile-creator/README.md
Labels: approved, lgtm

#518 bundle: make annotations consistent
  openshift-ci/Dockerfile.bundle.ci
  openshift-ci/Dockerfile.bundle.upstream.dev
Labels: approved, lgtm

#519 bundle: make annotations consistent
  openshift-ci/Dockerfile.bundle-4.7.ci
  openshift-ci/Dockerfile.bundle.ci
  openshift-ci/Dockerfile.bundle.upstream.dev
Labels: approved, lgtm
