Repository openshift-kni/performance-addon-operators, pull requests merged in 2021-03, with the labels that each got.

#567 gather_sysinfo: collect SMT state from sysfs
  tools/gather-sysinfo/gather-sysinfo.go
Labels: approved, lgtm

#568 Make the allocation logic more readable with helper functions
  pkg/profilecreator/profilecreator.go
  pkg/profilecreator/profilecreator_test.go
Labels: approved, lgtm

#569 pkg/profilecreator: Ensure targeted nodes have the same hardware
  cmd/performance-profile-creator/cmd/root.go
  go.mod
  go.sum
  hack/run-perf-profile-creator.sh
  pkg/profilecreator/mcp.go
  pkg/profilecreator/profilecreator.go
  pkg/profilecreator/profilecreator_test.go
  vendor/k8s.io/component-helpers/LICENSE
  vendor/k8s.io/component-helpers/scheduling/corev1/doc.go
  vendor/k8s.io/component-helpers/scheduling/corev1/helpers.go
  vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go
  vendor/modules.txt
Labels: approved, lgtm

#537 Advance ignition version
  go.mod
  go.sum
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  vendor/github.com/coreos/go-systemd/v22/LICENSE
  vendor/github.com/coreos/go-systemd/v22/NOTICE
  vendor/github.com/coreos/go-systemd/v22/unit/deserialize.go
  vendor/github.com/coreos/go-systemd/v22/unit/escape.go
  vendor/github.com/coreos/go-systemd/v22/unit/option.go
  vendor/github.com/coreos/go-systemd/v22/unit/serialize.go
  vendor/github.com/coreos/ignition/v2/LICENSE
  vendor/github.com/coreos/ignition/v2/NOTICE
  vendor/github.com/coreos/ignition/v2/config/shared/errors/errors.go
  vendor/github.com/coreos/ignition/v2/config/shared/validations/unit.go
  vendor/github.com/coreos/ignition/v2/config/util/helpers.go
  vendor/github.com/coreos/ignition/v2/config/util/interfaces.go
  vendor/github.com/coreos/ignition/v2/config/util/parsingErrors.go
  vendor/github.com/coreos/ignition/v2/config/util/reflection.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/config.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/custom.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/device.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/directory.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/disk.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/file.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/filesystem.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/headers.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/ignition.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/luks.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/mode.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/node.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/partition.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/passwd.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/path.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/proxy.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/raid.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/resource.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/schema.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/storage.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/tang.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/tls.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/unit.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/url.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/verification.go
  vendor/github.com/coreos/vcontext/LICENSE
  vendor/github.com/coreos/vcontext/path/path.go
  vendor/github.com/coreos/vcontext/report/report.go
  vendor/github.com/coreos/vcontext/tree/tree.go
  vendor/modules.txt
Labels: approved, lgtm

#573 Bug 1936953: remove the psr check from the rcu_nocbs test
  functests/1_performance/cpu_management.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#538 Generate a machine config name with the numerical prefix
  controllers/performanceprofile_controller.go
  controllers/performanceprofile_controller_test.go
  functests/0_config/config.go
  functests/1_performance/performance.go
  functests/utils/mcps/mcps.go
  hack/wait-for-mcp.sh
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
Labels: approved, lgtm

#574 [release-4.7] remove the psr check from the rcu_nocbs test
  functests/1_performance/cpu_management.go
Labels: approved, lgtm

#570 Validate user specified arguments and populate fields in the created Performance Profile
  cmd/performance-profile-creator/cmd/root.go
  pkg/profilecreator/profilecreator.go
  pkg/profilecreator/profilecreator_test.go
Labels: approved, lgtm

#577 Replace -M flag to --must-gather-dir-path in wrapper script
  hack/run-perf-profile-creator.sh
Labels: approved, lgtm

#575 Populate the additionalKernelArgs field in the performance profile
  cmd/performance-profile-creator/README.md
  cmd/performance-profile-creator/cmd/root.go
  pkg/profilecreator/profilecreator.go
  pkg/profilecreator/profilecreator_test.go
Labels: approved, lgtm

#580 must-gather: rename variable for clarity
  must-gather/collection-scripts/gather_nodes
Labels: approved, lgtm

#572 Net API including setting netqueues count on tuned
  api/v2/performanceprofile_types.go
  api/v2/performanceprofile_validation.go
  api/v2/performanceprofile_validation_test.go
  api/v2/zz_generated.deepcopy.go
  build/assets/tuned/openshift-node-performance
  config/crd/bases/performance.openshift.io_performanceprofiles.yaml
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance.openshift.io_performanceprofiles_crd.yaml
  docs/performance_profile.md
  functests/0_config/config.go
  functests/1_performance/performance.go
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
Labels: approved, lgtm

#571 must-gather: ghw: update dependency
  go.mod
  go.sum
  vendor/github.com/jaypipes/ghw/README.md
  vendor/github.com/jaypipes/ghw/SNAPSHOT.md
  vendor/github.com/jaypipes/ghw/alias.go
  vendor/github.com/jaypipes/ghw/pkg/context/context.go
  vendor/github.com/jaypipes/ghw/pkg/net/net.go
  vendor/github.com/jaypipes/ghw/pkg/net/net_linux.go
  vendor/github.com/jaypipes/ghw/pkg/option/option.go
  vendor/github.com/jaypipes/ghw/pkg/pci/address/address.go
  vendor/github.com/jaypipes/ghw/pkg/pci/pci.go
  vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_net.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_pci.go
  vendor/github.com/jaypipes/ghw/pkg/topology/topology.go
  vendor/modules.txt
Labels: approved, lgtm

#584 profilecreator: Support SNO clusters
  pkg/profilecreator/profilecreator.go
  pkg/profilecreator/profilecreator_test.go
  testdata/must-gather/must-gather.local.sno/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-0f7ae9cea65387b0497d6f9c28781e40f457b0f79838d65881ffb1aa779450a5/cluster-scoped-resources/core/nodes/ocp47sno-master-0.demo.lab.yaml
  testdata/must-gather/must-gather.local.sno/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-0f7ae9cea65387b0497d6f9c28781e40f457b0f79838d65881ffb1aa779450a5/cluster-scoped-resources/machineconfiguration.openshift.io/machineconfigpools/master.yaml
  testdata/must-gather/must-gather.local.sno/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-0f7ae9cea65387b0497d6f9c28781e40f457b0f79838d65881ffb1aa779450a5/cluster-scoped-resources/machineconfiguration.openshift.io/machineconfigpools/worker.yaml
  testdata/must-gather/must-gather.local.sno/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-0f7ae9cea65387b0497d6f9c28781e40f457b0f79838d65881ffb1aa779450a5/nodes/ocp47sno-master-0.demo.lab/sysinfo.tgz
Labels: approved, lgtm

#581 must-gather: align builder image to 4.8
  openshift-ci/Dockerfile.must-gather
Labels: approved, lgtm

#579 Turn off Tuned scheduler plugin dynamic tuning.
  build/assets/tuned/openshift-node-performance
Labels: approved, lgtm, ok-to-test

#585 profile-creator: Friendlier error messages
  cmd/performance-profile-creator/cmd/root.go
  pkg/profilecreator/profilecreator.go
Labels: approved, lgtm

#587 Enable disable-ht flag and user-level-networking in PPC
  cmd/performance-profile-creator/cmd/root.go
  pkg/profilecreator/profilecreator.go
  pkg/profilecreator/profilecreator_test.go
Labels: approved, lgtm

#586 profile-creator: Always add the MCP selector to the profile
  cmd/performance-profile-creator/cmd/root.go
  pkg/profilecreator/mcp.go
  pkg/profilecreator/profilecreator_test.go
Labels: approved, lgtm
