Repository openshift-kni/performance-addon-operators, pull requests merged in 2021-07, with the labels that each got.

#672 functests: handle empty `find` output
  functests/1_performance/cpu_management.go
Labels: approved, lgtm

#675 e2e: print stderr during the command execution
  functests/utils/utils.go
Labels: approved, lgtm

#677 [Release 4.8] Replace apiextensions v1beta1 with v1
  functests/utils/client/clients.go
Labels: approved, lgtm

#660 Missing required cmd flags
  cmd/performance-profile-creator/README.md
Labels: approved, lgtm, ok-to-test

#678 Set maximumLatency variable
  functests/4_latency/latency.go
Labels: approved, lgtm

#680 Add test case id to kernel argument managed_irq flag test case
  functests/1_performance/performance.go
Labels: approved, lgtm

#687 Latency tests: remove a condition which is always false
  functests/4_latency/latency.go
Labels: approved, lgtm

#691 add the OCP label index under metadata annotations
  deploy/metadata/performance-addon-operator/4.9.0/annotations.yaml
  hack/generate-metadata.sh
Labels: approved, lgtm

#690 e2e: Add stalld test and remove no longer needed skips
  functests/1_performance/performance.go
Labels: approved, lgtm, ok-to-test

#686 Enable the memory manager
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig_test.go
  testdata/render-expected-output/manual_kubeletconfig.yaml
Labels: approved, lgtm

#693 e2e: fix infra containers reserved CPUs test
  functests/1_performance/cpu_management.go
Labels: approved, lgtm

#694 e2e: replace the oc exec with oc rsh
  functests/utils/nodes/nodes.go
Labels: approved, lgtm

#692 [release-4.8] Cherry picked from PR "e2e: Add stalld test and remove no longer needed skips #690" Bug 1985365: "re-activate stalld test and add new stalld priority test"
  functests/1_performance/performance.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#651 Bug 1963951: Improve the logic behind setting PAO components labels and selectors
  api/v2/performanceprofile_types.go
  config/crd/bases/performance.openshift.io_performanceprofiles.yaml
  controllers/performanceprofile_controller.go
  controllers/performanceprofile_controller_test.go
  controllers/status.go
  deploy/olm-catalog/performance-addon-operator/4.9.0/performance.openshift.io_performanceprofiles_crd.yaml
  docs/performance_profile.md
  functests/1_performance/performance.go
  functests/utils/mcps/mcps.go
  functests/utils/profiles/profiles.go
  pkg/cmd/render/render.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig_test.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/controller/performanceprofile/components/manifestset/manifestset.go
  pkg/controller/performanceprofile/components/profile/profile.go
  pkg/controller/performanceprofile/components/profile/profile_test.go
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/utils/testing/testing.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#696 e2e: use REST client instead of oc to exec commands
  functests/1_performance/cpu_management.go
  functests/1_performance/hugepages.go
  functests/1_performance/performance.go
  functests/utils/pods/pods.go
  go.sum
  vendor/github.com/moby/spdystream/CONTRIBUTING.md
  vendor/github.com/moby/spdystream/LICENSE
  vendor/github.com/moby/spdystream/MAINTAINERS
  vendor/github.com/moby/spdystream/NOTICE
  vendor/github.com/moby/spdystream/README.md
  vendor/github.com/moby/spdystream/connection.go
  vendor/github.com/moby/spdystream/go.mod
  vendor/github.com/moby/spdystream/go.sum
  vendor/github.com/moby/spdystream/handlers.go
  vendor/github.com/moby/spdystream/priority.go
  vendor/github.com/moby/spdystream/spdy/dictionary.go
  vendor/github.com/moby/spdystream/spdy/read.go
  vendor/github.com/moby/spdystream/spdy/types.go
  vendor/github.com/moby/spdystream/spdy/write.go
  vendor/github.com/moby/spdystream/stream.go
  vendor/github.com/moby/spdystream/utils.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/pkg/util/remotecommand/constants.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/remotecommand/doc.go
  vendor/k8s.io/client-go/tools/remotecommand/errorstream.go
  vendor/k8s.io/client-go/tools/remotecommand/reader.go
  vendor/k8s.io/client-go/tools/remotecommand/remotecommand.go
  vendor/k8s.io/client-go/tools/remotecommand/resize.go
  vendor/k8s.io/client-go/tools/remotecommand/v1.go
  vendor/k8s.io/client-go/tools/remotecommand/v2.go
  vendor/k8s.io/client-go/tools/remotecommand/v3.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/k8s.io/client-go/util/exec/exec.go
  vendor/modules.txt
Labels: approved, lgtm

#697 Bug 1986006: e2e: fix oslat test
  functests/4_latency/latency.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#698 e2e: Reactivate and fix initramfs test
  functests/1_performance/performance.go
Labels: approved, lgtm

#699 Bug 1986399: Latency tests: disable irq and cpu load balancing
  functests/4_latency/latency.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#702 Broken link to the performance_profile.md
  docs/irq-load-balancing.md
Labels: approved, lgtm, ok-to-test

#703 Bug 1986410 Control CPUs amount under latency-test pod
  README.md
  functests/4_latency/latency.go
Labels: approved, lgtm
