Repository openshift-kni/performance-addon-operators, pull requests merged in 2021-09, with the labels that each got.

#725 Latency e2e: Report relevant error message upon invalid values
  functests/4_latency/latency.go
Labels: approved, lgtm

#726 Latency e2e: Add new negative test case and fix regex
  functests/4_latency/latency.go
  functests/5_latency_testing/latency_testing.go
Labels: approved, lgtm

#705 e2e: Modify regex for searching rcu{c,b} processes
  functests/1_performance/performance.go
Labels: approved, lgtm

#727 Align apis v1 and v2 to make sure we do not lose values during the conversion
  Makefile
  PROJECT
  api/v1/performanceprofile_types.go
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/performanceprofile_types.go
  api/v2/performanceprofile_conversion.go
  config/crd/bases/performance.openshift.io_performanceprofiles.yaml
  deploy/olm-catalog/performance-addon-operator/4.9.0/performance-addon-operator.v4.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.9.0/performance.openshift.io_performanceprofiles_crd.yaml
  functests/1_performance/performance.go
Labels: approved, lgtm

#731 Add metadata for 4.10 bundle container
  deploy/metadata/performance-addon-operator/4.10.0/annotations.yaml
Labels: approved, lgtm

#710 [release-4.8] Bug 1989531: Control CPUs amount under latency-test pod
  README.md
  functests/4_latency/latency.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#733 tuned: remove inline comments
  build/assets/tuned/openshift-node-performance
  testdata/render-expected-output/manual_tuned.yaml
Labels: approved, lgtm

#736 Bug 2006675: Test delay needs units to be valid duration
  functests/4_latency/latency.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#689 Disable debugging in gather_nodes script
  must-gather/collection-scripts/gather_nodes
Labels: ok-to-test, approved, lgtm

#738 Functional test - Performance addon operator pod should have CPU and memory requests set but not limits
  functests/1_performance/performance.go
Labels: ok-to-test, approved, lgtm

#734 Latency e2e: Check actual CPUs number and runtime
  functests/4_latency/latency.go
  functests/5_latency_testing/latency_testing.go
Labels: approved, lgtm

#743 Revert "Bug 2006675: Test delay needs units to be valid duration"
  functests/4_latency/latency.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium
