Repository openshift-kni/performance-addon-operators, pull requests merged in 2021-12, with the labels that each got.

#791 vendor: update debug-tools dependency
  go.mod
  go.sum
  vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/k8s/podres.go
  vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/k8s/types.go
  vendor/modules.txt
Labels: approved, lgtm

#794 Update OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: approved, lgtm

#792 Set isolated and required CPU parameter in CRD
  api/v2/performanceprofile_types.go
  config/crd/bases/performance.openshift.io_performanceprofiles.yaml
  deploy/olm-catalog/performance-addon-operator/4.10.0/performance.openshift.io_performanceprofiles_crd.yaml
  docs/performance_profile.md
Labels: approved, lgtm

#802 Pin ginkgo version in Dockerfile.tools
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#805 Enable go modules in Dockerfile.tools
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#797 controller: watch tuned profiles for changes under the status
  controllers/performanceprofile_controller.go
Labels: approved, lgtm

#801 Update OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: approved, lgtm

#803 Pin ginkgo version in Dockerfile.tools
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#809 Update OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: approved, lgtm

#804 Pin ginkgo version in Dockerfile.tools
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#806 controller: fix kubeletconfig predicates
  controllers/performanceprofile_controller.go
Labels: approved, lgtm

#810 Update OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: approved, lgtm

#811 Update OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: approved, lgtm

#814 tuned base profile to support new scheduler nobs
  build/assets/tuned/openshift-node-performance
  testdata/render-expected-output/manual_tuned.yaml
Labels: approved, lgtm

#816 Add clean to make generate to avoid _output garbage issues
  Makefile
Labels: approved, lgtm

#817 Latency tests: skip running open BZ scenarios
  functests/5_latency_testing/latency_testing.go
Labels: approved, lgtm

#821 [release-4.8] Bug 2034179: controller: watch tuned profiles for changes under the status
  controllers/performanceprofile_controller.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#795 Bug 2034484: feat: library-go bump and leader election conventions
  config/rbac/role.yaml
  controllers/performanceprofile_controller.go
  deploy/olm-catalog/performance-addon-operator/4.10.0/performance-addon-operator.v4.10.0.clusterserviceversion.yaml
  go.mod
  go.sum
  main.go
  pkg/utils/leaderelection/leaderelection.go
  vendor/github.com/openshift/client-go/LICENSE
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/scheduler.go
  vendor/github.com/openshift/library-go/LICENSE
  vendor/github.com/openshift/library-go/pkg/config/clusterstatus/clusterstatus.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, ok-to-test, approved, lgtm, bugzilla/severity-high
