Repository openshift-kni/performance-addon-operators, pull requests merged in 2021-06, with the labels that each got.

#643 Bug 1957291: add resource request and toleration's to the operator
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml
  tools/csv-processor/csv-processor.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#625 Increase tests timeout for single node test environments
  functests/0_config/config.go
  functests/1_performance/cpu_management.go
  functests/1_performance/hugepages.go
  functests/1_performance/performance.go
  functests/utils/cluster/cluster.go
  functests/utils/mcps/mcps.go
Labels: approved, lgtm

#640 update the contributor groups
  OWNERS_ALIASES
Labels: approved, lgtm

#644 functests: better error message on failure
  functests/1_performance/cpu_management.go
Labels: approved, lgtm

#638 [release 4.7] Enabled stalld only from a minimum openshift release
  build/assets/tuned/openshift-node-performance
  config/rbac/role.yaml
  controllers/performanceprofile_controller.go
  controllers/performanceprofile_controller_test.go
  deploy/olm-catalog/performance-addon-operator/4.7.4/performance-addon-operator.v4.7.4.clusterserviceversion.yaml
  functests/1_performance/performance.go
  go.mod
  go.sum
  main.go
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
  vendor/github.com/hashicorp/go-version/CHANGELOG.md
  vendor/github.com/hashicorp/go-version/LICENSE
  vendor/github.com/hashicorp/go-version/README.md
  vendor/github.com/hashicorp/go-version/constraint.go
  vendor/github.com/hashicorp/go-version/go.mod
  vendor/github.com/hashicorp/go-version/version.go
  vendor/github.com/hashicorp/go-version/version_collection.go
  vendor/modules.txt
Labels: approved, lgtm

#646 [release 4.6] Enabled stalld only from a minimum openshift release
  build/assets/tuned/openshift-node-performance
  cmd/manager/main.go
  deploy/olm-catalog/performance-addon-operator/4.6.4/performance-addon-operator.v4.6.4.clusterserviceversion.yaml
  deploy/role.yaml
  functests/1_performance/performance.go
  go.mod
  go.sum
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
  pkg/controller/performanceprofile/performanceprofile_controller.go
  pkg/controller/performanceprofile/performanceprofile_controller_test.go
  vendor/github.com/hashicorp/go-version/.travis.yml
  vendor/github.com/hashicorp/go-version/LICENSE
  vendor/github.com/hashicorp/go-version/README.md
  vendor/github.com/hashicorp/go-version/constraint.go
  vendor/github.com/hashicorp/go-version/go.mod
  vendor/github.com/hashicorp/go-version/version.go
  vendor/github.com/hashicorp/go-version/version_collection.go
  vendor/modules.txt
Labels: approved, lgtm

#647 Provide the runtime class documentation
  docs/runtime-class.md
Labels: approved, lgtm

#654 [release-4.6] Bump upstream bundle z-stream version
  openshift-ci/Dockerfile.bundle.upstream.dev
Labels: approved, lgtm

#655 [release-4.7] Advance 4.6 bundle z-stream version
  deploy/metadata/performance-addon-operator/4.5.1/annotations.yaml
  deploy/metadata/performance-addon-operator/4.6.4/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.0/performance-addon-operator.v4.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.0/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.0/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.4/performance-addon-operator.v4.6.4.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.4/performance.openshift.io_performanceprofiles_crd.yaml
  openshift-ci/Dockerfile.bundle-4.6.ci
Labels: approved, lgtm

#645 Improve error output for render E2E test
  functests-render-command/1_render_command/render_suite_test.go
  functests-render-command/1_render_command/render_test.go
  go.mod
  vendor/modules.txt
Labels: approved, lgtm

#649 [release-4.7] Fix code to test number of Hugepages per numa node
  functests/2_performance_update/updating_profile.go
  functests/utils/nodes/nodes.go
Labels: approved, lgtm

#656 [release-4.8] Advance 4.7 bundle z-stream version
  deploy/metadata/performance-addon-operator/4.5.1/annotations.yaml
  deploy/metadata/performance-addon-operator/4.6.0/annotations.yaml
  deploy/metadata/performance-addon-operator/4.7.4/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.0/performance-addon-operator.v4.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.0/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.0/performance-addon-operator.v4.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.0/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.1/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/4.7.4/performance-addon-operator.v4.7.4.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.7.4/performance.openshift.io_performanceprofiles_crd.yaml
  openshift-ci/Dockerfile.bundle-4.6.ci
  openshift-ci/Dockerfile.bundle-4.7.ci
Labels: approved, lgtm

#641 Performance Profile creator tests
  functests-performance-profile-creator/1_performance-profile_creator/ppc.go
  testdata/ppc-expected-profiles/profile3.json
  testdata/ppc-expected-profiles/profile3.yaml
  testdata/ppc-expected-profiles/profile4.json
  testdata/ppc-expected-profiles/profile4.yaml
  testdata/ppc-expected-profiles/profile5.json
  testdata/ppc-expected-profiles/profile5.yaml
Labels: approved, lgtm

#661 e2e: provide correct timeout for tuned tests
  functests/1_performance/performance.go
Labels: approved, lgtm

#663 [Release 4.5] Bump to 4.5.5 and remove redundancy in bump script
  deploy/metadata/performance-addon-operator/4.5.5/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.5/performance-addon-operator.v4.5.5.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.5/performance.openshift.io_performanceprofiles_crd.yaml
  hack/bump-zversion.sh
  hack/common.sh
  openshift-ci/Dockerfile.bundle.ci
Labels: approved, lgtm

#657 functests: improve messages
  functests/1_performance/performance.go
Labels: approved, lgtm

#658 functests: utils: add ExecAndLogCommandWithStderr
  functests-performance-profile-creator/1_performance-profile_creator/ppc.go
  functests/utils/utils.go
Labels: approved, lgtm

#665 Fix discovery mode tests on SNO
  functests/utils/consts.go
Labels: approved, lgtm

#659 Bug 1967317: Do not create systemd update-rps service for veth devices
  build/assets/configs/99-netdev-rps.rules
  build/assets/scripts/low-latency-hooks.sh
  testdata/render-expected-output/manual_machineconfig.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#669 Merge pull request #639 from fromanirh/e2e-irqbalance-fix
  functests/2_performance_update/updating_profile.go
  functests/utils/nodes/nodes.go
  pkg/controller/performanceprofile/components/utils.go
Labels: approved, lgtm

#668 Bug 1947070: e2e: change skip message for IRQ load balancing test
  functests/1_performance/cpu_management.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#671 Provide an example for the render command use
  README.md
Labels: approved, lgtm

#667 [release-4.8] Bug 1975348: Do not create systemd update-rps service for veth devices
  build/assets/configs/99-netdev-rps.rules
  build/assets/scripts/low-latency-hooks.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#664 Add test for cyclictest and hwlatetect binaries under cnf-tests image
  functests/4_latency/latency.go
Labels: approved, lgtm

#674 automated 1972701 bug verification
  functests/1_performance/performance.go
Labels: approved, lgtm, ok-to-test
