Repository openshift-kni/performance-addon-operators, pull requests merged in 2021-04, with the labels that each got.

#591 Change upgrade test installPlanApproval to Automatic
  functests-extended/1_performance_operator_upgrade/upgrade_operator.go
Labels: approved, lgtm

#588 must-gather: fix warnings
  must-gather/collection-scripts/gather_nodes
Labels: approved, lgtm

#590 Dockerfile: use modern ENV syntax
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#589 Netqueues support for vendor and model
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
Labels: approved, lgtm

#592 Change net api fields to more logical names
  api/v2/performanceprofile_types.go
  config/crd/bases/performance.openshift.io_performanceprofiles.yaml
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance.openshift.io_performanceprofiles_crd.yaml
  docs/performance_profile.md
Labels: approved, lgtm

#583 Consume NTO's per-node Tuned profile application status
  config/rbac/role.yaml
  controllers/performanceprofile_controller.go
  controllers/performanceprofile_controller_test.go
  controllers/status.go
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml-merge-patch
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml-merge-patch
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml-merge-patch
  vendor/github.com/openshift/api/operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-merge-patch
  vendor/github.com/openshift/api/operator/v1/0000_50_service-ca-operator_02_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/doc.go
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_config.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_csi_snapshot.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_kubestorageversionmigrator.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_scheduler.go
  vendor/github.com/openshift/api/operator/v1/types_serviceca.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_servicecatalogcontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/tuned_types.go
  vendor/github.com/openshift/cluster-node-tuning-operator/pkg/apis/tuned/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#594 Remove superfluous rbac permissions
  config/rbac/role.yaml
  controllers/performanceprofile_controller.go
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml
Labels: approved, lgtm

#593 Add myself under reviewers list
  OWNERS_ALIASES
Labels: approved, lgtm

#596 Fix net tuned generation
  build/assets/tuned/openshift-node-performance
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
Labels: approved, lgtm

#595 profile-creator: Add E2E regression tests
  Makefile
  cmd/performance-profile-creator/cmd/root.go
  functests-performance-profile-creator/1_performance-profile_creator/performance_profile_creator_suite_test.go
  functests-performance-profile-creator/1_performance-profile_creator/ppc.go
  hack/run-perf-profile-creator-functests.sh
  pkg/profilecreator/profilecreator_test.go
  testdata/must-gather/must-gather.bare-metal/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/core/nodes/master1.yaml
  testdata/must-gather/must-gather.bare-metal/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/core/nodes/master2.yaml
  testdata/must-gather/must-gather.bare-metal/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/core/nodes/master3.yaml
  testdata/must-gather/must-gather.bare-metal/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/core/nodes/worker1.yaml
  testdata/must-gather/must-gather.bare-metal/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/core/nodes/worker2.yaml
  testdata/must-gather/must-gather.bare-metal/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/machineconfiguration.openshift.io/machineconfigpools/master.yaml
  testdata/must-gather/must-gather.bare-metal/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/machineconfiguration.openshift.io/machineconfigpools/worker-cnf.yaml
  testdata/must-gather/must-gather.bare-metal/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/machineconfiguration.openshift.io/machineconfigpools/worker.yaml
  testdata/must-gather/must-gather.bare-metal/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/nodes/worker1/sysinfo.tgz
  testdata/must-gather/must-gather.bare-metal/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/nodes/worker2/sysinfo.tgz
  testdata/must-gather/must-gather.sno/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-0f7ae9cea65387b0497d6f9c28781e40f457b0f79838d65881ffb1aa779450a5/cluster-scoped-resources/core/nodes/ocp47sno-master-0.demo.lab.yaml
  testdata/must-gather/must-gather.sno/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-0f7ae9cea65387b0497d6f9c28781e40f457b0f79838d65881ffb1aa779450a5/cluster-scoped-resources/machineconfiguration.openshift.io/machineconfigpools/master.yaml
  testdata/must-gather/must-gather.sno/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-0f7ae9cea65387b0497d6f9c28781e40f457b0f79838d65881ffb1aa779450a5/cluster-scoped-resources/machineconfiguration.openshift.io/machineconfigpools/worker.yaml
  testdata/must-gather/must-gather.sno/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-0f7ae9cea65387b0497d6f9c28781e40f457b0f79838d65881ffb1aa779450a5/nodes/ocp47sno-master-0.demo.lab/sysinfo.tgz
  testdata/ppc-expected-profiles/profile1.json
  testdata/ppc-expected-profiles/profile1.yaml
  testdata/ppc-expected-profiles/profile2.json
  testdata/ppc-expected-profiles/profile2.yaml
Labels: approved, lgtm

#597 Add management workload annotations
  cluster-setup/base/performance/operator_namespace.yaml
  config/manager/manager.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.0/performance-addon-operator.v4.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.0/performance-addon-operator.v4.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.7.0/performance-addon-operator.v4.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml
  must-gather/node-gather/daemonset.yaml
  must-gather/node-gather/namespace.yaml
Labels: approved, lgtm

#602 Bug 1947070: remove internal JIRA link from the IRQ load balancing test
  functests/1_performance/cpu_management.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#607 profile-creator: do not consider MCPs targeting unschedulable nodes
  cmd/performance-profile-creator/cmd/root.go
  pkg/profilecreator/mcp.go
Labels: approved, lgtm

#599 Advance go version to 1.16.3
  go.sum
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#604 version: bump to 4.7.2
  deploy/metadata/performance-addon-operator/4.7.2/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.7.2/performance-addon-operator.v4.7.2.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.7.2/performance.openshift.io_performanceprofiles_crd.yaml
  hack/common.sh
  openshift-ci/Dockerfile.bundle.ci
  openshift-ci/Dockerfile.bundle.upstream.dev
Labels: approved, lgtm

#611 [release-4.5] Change upgrade test installPlanApproval to Automatic
  functests-extended/1_performance_operator_upgrade/upgrade_operator.go
Labels: approved, lgtm

#612 bump version to 4.6.3
  deploy/metadata/performance-addon-operator/4.6.3/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.3/performance-addon-operator.v4.6.3.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.3/performance.openshift.io_performanceprofiles_crd.yaml
  hack/common.sh
  openshift-ci/Dockerfile.bundle.ci
Labels: approved, lgtm

#600 Bug 1947773: Re-enable stalld
  build/assets/tuned/openshift-node-performance
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#614 release 4.5.4
  deploy/metadata/performance-addon-operator/4.5.4/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.4/performance-addon-operator.v4.5.4.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.4/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  hack/common.sh
  hack/csv-generate.sh
  openshift-ci/Dockerfile.bundle.ci
Labels: approved, lgtm

#615 Ensure PPC binary is created before running PPC functional tests
  Makefile
Labels: approved, lgtm

#601 performance-creator: Don't add the 'userLevelNetworking' field by default
  cmd/performance-profile-creator/cmd/root.go
  functests-performance-profile-creator/1_performance-profile_creator/ppc.go
  testdata/ppc-expected-profiles/profile1.yaml
  testdata/ppc-expected-profiles/profile2.json
Labels: approved, lgtm

#598 E2E test for consume NTO's per-node Tuned profile application status
  functests/3_performance_status/status.go
  functests/utils/profiles/profiles.go
Labels: approved, lgtm

#618 ghw: consume latest fixes
  go.mod
  go.sum
  vendor/github.com/jaypipes/ghw/README.md
  vendor/github.com/jaypipes/ghw/pkg/context/context.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_cache_linux.go
  vendor/github.com/jaypipes/ghw/pkg/pci/pci.go
  vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_block.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/pack.go
  vendor/modules.txt
Labels: approved, lgtm

#603 Bug 1945010: Update CPU Section in PAO Doc
  api/v1/performanceprofile_types.go
  config/crd/bases/performance.openshift.io_performanceprofiles.yaml
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance.openshift.io_performanceprofiles_crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#619 Rename workload annotations
  config/manager/manager.yaml
  deploy/olm-catalog/performance-addon-operator/4.4.0/performance-addon-operator.v4.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.0/performance-addon-operator.v4.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.7.0/performance-addon-operator.v4.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml
  must-gather/node-gather/daemonset.yaml
Labels: approved, lgtm

#621 [release-4.6] Bug 1949027: Re-enable stalld
  build/assets/tuned/openshift-node-performance
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
