Repository openshift-kni/performance-addon-operators, pull requests merged in 2021-02, with the labels that each got.

#522 Bug 1923220: Do not install and enable stalld service
  build/assets/tuned/openshift-node-performance
  functests/1_performance/performance.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#512 Bug 1918788: Avoid unneeded object initialization during profile conversion
  api/v1alpha1/performanceprofile_conversion.go
  api/v2/performanceprofile_conversion.go
  functests/1_performance/performance.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#526 deps: bump ghw to 0.7.0
  go.mod
  go.sum
  vendor/github.com/jaypipes/ghw/pkg/option/option.go
  vendor/modules.txt
Labels: approved, lgtm

#527 Update tools image to use ubi8
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#461 Fix the expected kubeletconfig failure condition status
  controllers/status.go
Labels: approved, lgtm

#521 hack: Add run-perf-profile-creator wrapper
  cmd/performance-profile-creator/README.md
  hack/run-perf-profile-creator.sh
Labels: approved, lgtm

#532 must-gather: use 'Always' pull policy
  must-gather/node-gather/daemonset.yaml
Labels: approved, lgtm

#533 e2e: fix the IRQ load balancing test to work properly with nosmt
  functests/1_performance/cpu_management.go
Labels: approved, lgtm

#467 Implement validation webhook
  api/v1/performanceprofile_webhook.go
  api/v2/performanceprofile_validation.go
  api/v2/performanceprofile_validation_suite_test.go
  api/v2/performanceprofile_validation_test.go
  api/v2/performanceprofile_webhook.go
  api/v2/zz_generated.deepcopy.go
  controllers/performanceprofile_controller.go
  controllers/performanceprofile_controller_test.go
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml
  functests/1_performance/performance.go
  functests/3_performance_status/status.go
  main.go
  pkg/controller/performanceprofile/components/profile/profile.go
  pkg/controller/performanceprofile/components/profile/profile_test.go
  tools/csv-processor/csv-processor.go
Labels: approved, lgtm

#510 csv: icon: update with new one
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml
  docs/pao-icon.svg
Labels: approved, lgtm

#535 Provide v1alpha1 performance profile example under the CSV
  config/samples/kustomization.yaml
  config/samples/performance_v1alpha1_performanceprofile.yaml
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml
Labels: approved, lgtm

#539 [release-4.6] comment the stalld section
  build/assets/tuned/openshift-node-performance
Labels: approved, lgtm

#540 Add MCP as an argument and mark certain flags as required
  cmd/performance-profile-creator/cmd/root.go
Labels: approved, lgtm

#541 No profile creation in case PPC is run with --help/-h
  cmd/performance-profile-creator/cmd/root.go
Labels: approved, lgtm

#520 hack: add helper to bump the zversion
  Makefile
  hack/bump-zversion.sh
Labels: approved, lgtm

#542 Update the bundle used to generate index image
  openshift-ci/Dockerfile.index-gen.ci
Labels: approved, lgtm

#545 Update discovery mode performance profile selector to choose by NODE_SELECTOR environment variable
  functests/utils/consts.go
  functests/utils/discovery/discovery.go
Labels: approved, lgtm

#547 [release 4.6] Add bump tool and bump version to 4.6.2
  Makefile
  deploy/metadata/performance-addon-operator/4.6.2/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.2/performance-addon-operator.v4.6.2.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.6.2/performance.openshift.io_performanceprofiles_crd.yaml
  hack/bump-zversion.sh
  hack/common.sh
  openshift-ci/Dockerfile.bundle.ci
Labels: approved, lgtm

#514 must-gather: gather sysinfo from host data
  must-gather/collection-scripts/gather_nodes
  must-gather/node-gather/daemonset.yaml
  tools/gather-sysinfo/gather-sysinfo.go
Labels: approved, lgtm

#550 Makefile: make sure the default target is "build"
  Makefile
Labels: approved, lgtm

#552 must-gather: sysinfo: direct copy using stdout
  must-gather/collection-scripts/gather_nodes
  tools/gather-sysinfo/gather-sysinfo.go
Labels: approved, lgtm

#556 Makefile: smoothen targets
  Makefile
Labels: approved, lgtm

#557 Bug 1930107: Comment the stalld section to prevent stalld installation
  build/assets/tuned/openshift-node-performance
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#558 must-gather: bump up gather pod memory limit
  must-gather/node-gather/daemonset.yaml
Labels: approved, lgtm

#561 release-4.5: prepare for 4.5.3 release
  deploy/metadata/performance-addon-operator/4.5.2/annotations.yaml
  deploy/metadata/performance-addon-operator/4.5.3/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.3/performance-addon-operator.v4.5.3.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.5.3/performance.openshift.io_performanceprofiles_crd.yaml
  deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
  hack/common.sh
  hack/csv-generate.sh
Labels: approved, lgtm

#555 must-gather: sysinfo: make sure we copy ghw files
  tools/gather-sysinfo/gather-sysinfo.go
Labels: approved, lgtm

#560 Create CI lane to validate u/s targets and tooling
  Makefile
  hack/verify-tools.sh
Labels: approved, lgtm, ok-to-test

#549 Find the nodes targeted by an MCP
  cmd/performance-profile-creator/cmd/root.go
  go.mod
  go.sum
  pkg/profilecreator/helper.go
  pkg/profilecreator/profilecreator.go
  pkg/profilecreator/profilecreator_suite_test.go
  pkg/profilecreator/profilecreator_test.go
  testdata/must-gather/must-gather.local.directory/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/core/nodes/cnfd1-worker-0.fci1.kni.lab.eng.bos.redhat.com.yaml
  testdata/must-gather/must-gather.local.directory/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/core/nodes/dhcp19-232-222.fci1.kni.lab.eng.bos.redhat.com.yaml
  testdata/must-gather/must-gather.local.directory/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/core/nodes/dhcp19-232-223.fci1.kni.lab.eng.bos.redhat.com.yaml
  testdata/must-gather/must-gather.local.directory/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/core/nodes/dhcp19-232-231.fci1.kni.lab.eng.bos.redhat.com.yaml
  testdata/must-gather/must-gather.local.directory/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/core/nodes/dhcp19-232-239.fci1.kni.lab.eng.bos.redhat.com.yaml
  testdata/must-gather/must-gather.local.directory/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/machineconfiguration.openshift.io/machineconfigpools/master.yaml
  testdata/must-gather/must-gather.local.directory/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/machineconfiguration.openshift.io/machineconfigpools/worker-cnf.yaml
  testdata/must-gather/must-gather.local.directory/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/cluster-scoped-resources/machineconfiguration.openshift.io/machineconfigpools/worker.yaml
  testdata/must-gather/must-gather.local.directory/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/nodes/cnfd1-worker-0.fci1.kni.lab.eng.bos.redhat.com/sysinfo.tgz
  testdata/must-gather/must-gather.local.directory/quay-io-openshift-kni-performance-addon-operator-must-gather-sha256-09d31edb2171e1fe385df1238ce5a6f7ca3556efa271550a7e98e26dce290128/nodes/dhcp19-232-239.fci1.kni.lab.eng.bos.redhat.com/sysinfo.tgz
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/go-logr/zapr/README.md
  vendor/github.com/go-logr/zapr/go.mod
  vendor/github.com/go-logr/zapr/zapr.go
  vendor/k8s.io/component-helpers/LICENSE
  vendor/k8s.io/component-helpers/scheduling/corev1/doc.go
  vendor/k8s.io/component-helpers/scheduling/corev1/helpers.go
  vendor/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/SECURITY.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: approved, lgtm

#563 e2e: skip the IRQ load balancing test
  functests/1_performance/cpu_management.go
Labels: approved, lgtm

#564 [release 4.7.1] Add bump tool and bump version to 4.7.1
  Makefile
  deploy/metadata/performance-addon-operator/4.7.1/annotations.yaml
  deploy/olm-catalog/performance-addon-operator/4.7.1/performance-addon-operator.v4.7.1.clusterserviceversion.yaml
  deploy/olm-catalog/performance-addon-operator/4.7.1/performance.openshift.io_performanceprofiles_crd.yaml
  hack/bump-zversion.sh
  hack/common.sh
  openshift-ci/Dockerfile.bundle.ci
  openshift-ci/Dockerfile.bundle.upstream.dev
Labels: approved, lgtm

#548 Bug 1885317: Provide a log package that will write to GinkgoWriter
  functests/0_config/config.go
  functests/1_performance/cpu_management.go
  functests/1_performance/performance.go
  functests/1_performance/test_suite_performance_test.go
  functests/2_performance_update/test_suite_performance_update_test.go
  functests/3_performance_status/test_suite_performance_status_test.go
  functests/4_latency/latency.go
  functests/4_latency/test_suite_latency_test.go
  functests/utils/clean/clean.go
  functests/utils/client/clients.go
  functests/utils/discovery/discovery.go
  functests/utils/log/log.go
  functests/utils/mcps/mcps.go
  functests/utils/nodes/nodes.go
  functests/utils/profiles/profiles.go
  functests/utils/utils.go
Labels: approved, lgtm

#553 tests: clarify failure reasons
  functests/0_config/config.go
  functests/1_performance/cpu_management.go
  functests/1_performance/hugepages.go
  functests/1_performance/performance.go
  functests/1_performance/rt-kernel.go
  functests/1_performance/test_suite_performance_test.go
  functests/1_performance/topology_manager.go
  functests/2_performance_update/updating_profile.go
  functests/3_performance_status/status.go
  functests/4_latency/latency.go
  functests/utils/client/clients.go
  functests/utils/mcps/mcps.go
  functests/utils/profiles/profiles.go
Labels: approved, lgtm
