Repository openshift-kni/performance-addon-operators, pull requests merged in 2022-02, with the labels that each got.

#831 Bug 2046463: Switch to node-device nested maps for netqueues tests
  functests/1_performance/netqueues.go
  functests/utils/nodes/nodes.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#833 Embed assets under the go compiled code
  build/assets/assets.go
  controllers/performanceprofile_controller.go
  controllers/performanceprofile_controller_test.go
  functests/1_performance/performance.go
  main.go
  openshift-ci/Dockerfile.deploy
  pkg/cmd/render/render.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
  pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
  pkg/controller/performanceprofile/components/manifestset/manifestset.go
  pkg/controller/performanceprofile/components/tuned/tuned.go
  pkg/controller/performanceprofile/components/tuned/tuned_test.go
Labels: approved, lgtm

#836 Latency e2e: fix skipping report when cpus amount is less than minimum
  functests/4_latency/latency.go
  functests/5_latency_testing/latency_testing.go
Labels: approved, lgtm

#838 e2e upgrade: wait for other components to handle PAO resources updates
  functests-extended/1_performance_operator_upgrade/upgrade_operator.go
  functests/utils/tuned/tuned.go
Labels: approved, lgtm

#837 [release-4.10] Bug 2050105: Switch to node-device nested maps
  functests/1_performance/netqueues.go
  functests/utils/nodes/nodes.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#840 controller: do not truncate original errors
  controllers/performanceprofile_controller.go
Labels: approved, lgtm

#842 e2e upgrade: drop W/A for OLM bug
  functests-extended/1_performance_operator_upgrade/upgrade_operator.go
Labels: approved, lgtm

#841 fix netqueues device tests
  functests/1_performance/netqueues.go
Labels: approved, lgtm

#848 Allow more update time for netqueues tests
  functests/1_performance/netqueues.go
Labels: approved, lgtm

#851 e2e (netqueues): do not skip from called functions
  functests/1_performance/netqueues.go
Labels: approved, lgtm

#853 Remove ineffective if assignment on controller
  controllers/performanceprofile_controller.go
Labels: ok-to-test, approved, lgtm

#825 BZ 1967911: E2E Test cases for enabling unsafe sysctl in performance profile
  functests/2_performance_update/kubelet.go
Labels: approved, lgtm
