Repository openshift-kni/performance-addon-operators, pull requests merged in 2022-01, with the labels that each got.

#793 Bug 2018443 - On a DU node deployed via ZTP process the performance-operator pod has limits set
  functests/1_performance/performance.go
Labels: ok-to-test, approved, lgtm

#808 Bug 2033292: [Release 4.8] Set isolated and required CPU parameter in CRD
  api/v2/performanceprofile_types.go
  config/crd/bases/performance.openshift.io_performanceprofiles.yaml
  deploy/olm-catalog/performance-addon-operator/4.8.0/performance.openshift.io_performanceprofiles_crd.yaml
  docs/performance_profile.md
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#822 Bug 2021202: Enable PAO image precaching
  config/manager/manager.yaml
  deploy/olm-catalog/performance-addon-operator/4.10.0/performance-addon-operator.v4.10.0.clusterserviceversion.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-low

#711 [release-4.7] Bug 1989536: Control CPUs amount under latency-test pod
  README.md
  functests/4_latency/latency.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#826 e2e: Add missing TCs IDs
  functests/1_performance/cpu_management.go
Labels: approved, lgtm

#828 hack: show cluster version before to run functests
  Makefile
  hack/show-cluster-version.sh
Labels: approved, lgtm

#824 k8s: deps: bump minimal version to 1.23
  deploy/olm-catalog/performance-addon-operator/4.10.0/performance-addon-operator.v4.10.0.clusterserviceversion.yaml
  hack/common.sh
Labels: approved, lgtm

#830 enable cpumanager policy options - full-pcpus-only
  functests/1_performance/cpu_management.go
  functests/utils/nodes/nodes.go
  functests/utils/pods/pods.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig.go
  pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig_test.go
  testdata/render-expected-output/manual_kubeletconfig.yaml
Labels: approved, lgtm

#832 deps: consume kube 1.23.3
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/errors.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched.go
  vendor/golang.org/x/net/http2/writesched_random.go
  vendor/golang.org/x/net/idna/go118.go
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/pre_go118.go
  vendor/golang.org/x/net/idna/punycode.go
  vendor/k8s.io/api/autoscaling/v2beta1/types.go
  vendor/k8s.io/api/autoscaling/v2beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/autoscaling/v2beta2/types.go
  vendor/k8s.io/api/autoscaling/v2beta2/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/flowcontrol/v1alpha1/types.go
  vendor/k8s.io/api/flowcontrol/v1alpha1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/flowcontrol/v1beta1/types.go
  vendor/k8s.io/api/flowcontrol/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/client-go/tools/pager/pager.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
Labels: approved, lgtm
